In [247]:
pwd

'/Users/keenanburkepitts/Documents/Data_Science/NYC_DSA/final_project'

In [248]:
ls

Craigslist_items.json               fb_used_items_filtered.txt
FBM_selenium.py                     final_project/
Facebook_items.json                 final_project_EDA_and_NLP.ipynb
Letgo_items.json                    final_project_data_wrangling.ipynb
all_items_cleaned.csv               geckodriver.log
cl_items_cleaned.csv                lg_items_cleaned.csv
cl_used_items_filtered.txt          lg_used_items_filtered.txt
connxchange_FBM.py                  notes.txt
fb_items_cleaned.csv

In [249]:
import json
import pandas as pd
import numpy as np
import re
pd.options.display.max_colwidth = 500

In [250]:
def load_json_files_into_list(file):
    #loading raw json files into lists 
    used_items_raw = []
    with open(file) as json_file:
        if "Facebook" in file:
            for line in json_file:
                used_items_raw.append(json.loads(line))
        elif "Letgo" in file:
            for line in json_file:
                used_items_raw.append(json.loads(line))
        else:
            for line in json_file:
                used_items_raw.append(json.loads(line))            
        return used_items_raw
    json_file.close()
    

fb_used_items_raw = load_json_files_into_list('Facebook_items.json')

print(len(fb_used_items_raw))

lg_used_items_raw = load_json_files_into_list("Letgo_items.json")

print(len(lg_used_items_raw))

cl_used_items_raw = load_json_files_into_list("Craigslist_items.json")

print(len(cl_used_items_raw))

2737
5000
2909

In [251]:
fb_used_items_raw[0]

{'Date_Time': '19 hours ago',
 'Description': 'I am looking to trade for a good lawnmower trailer... this trailer has no title well built home made can take to DMV to get a title if you want to..... 2 tires are bad and no ramps',
 'Images': ['https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/28166358_10155420186467406_7310413144723681998_n.jpg?oh=93f1e4a5b48a075229713d25cf258133&oe=5B015F1C',
  'https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/28378821_10155420186517406_1897625093764673220_n.jpg?oh=c17b35d5a0c8c9a3eaf9b4ce85f8b318&oe=5B4E122E',
  'https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/28056607_10155420186547406_7242013894880377437_n.jpg?oh=39fb0cf9cfc2f7ba894ebdc4a02fd6b9&oe=5B07DEF5',
  'https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/28167334_10155420186612406_2404951221271124280_n.jpg?oh=e5e6e88f8f33f024d3669cbe385089f7&oe=5B1DB2A2',
  'https://scontent-iad3-1.xx.fbcdn.net/v/t1.0-9/27973889_10155420186652406_3252997498365045774_n.jpg?oh=332817a55b838cd695f28c7ec3439d08&oe=5B160114'],
 'Location': 'Forest City, NC',
 'Price': 'FREE',
 'Title': 'Traier',
 'Url': 'https://www.facebook.com/marketplace/item/150586762282415',
 '_id': {'$oid': '5a8ed8b3a9750f0a93663b92'}}

In [252]:
lg_used_items_raw[0]

{'Date': '2018-02-21T23:43:44+00:00',
 'Description': '',
 'Images': ['https://img.letgo.com/images/c3/4f/21/bb/c34f21bbb74a8f70435c516290b2cffd.jpeg'],
 'Latitude': 35.46224831,
 'Location': 'Canton',
 'Longitude': -82.86450999,
 'Price': 200,
 'Title': 'brown wooden console table',
 'Url': 'https://us.letgo.com/en/i/brown-wooden-console-table_d493fd46-f892-4a31-85bb-e66f089714ba',
 '_id': {'$oid': '5a8e04df6f9ca507bf9824ae'}}

In [253]:
cl_used_items_raw[0]

{'Condition': '2013 Yamaha FJR 1300',
 'Date': '2018-02-28 11:30',
 'Description': ['\n        ',
  '\n2013 Yamaha FJR 1300 Sport Touring, 4 cylinder, 12.120 miles, silver, cruise control, traction control, ABS brakes, heated hand grips, Two Brothers exhaust, handle bar risers, 6.5 gal. gas tank, adjustable windshield, saddlebags, excellent condition, very clean.',
  '\n$ 7.500 (828) 250-0373 WWW.GREENVALLEYCARS.COM',
  '\n',
  '\n    '],
 'Images': [],
 'Latitude': '35.599694',
 'Location': ' (Asheville)',
 'Longitude': '-82.628866',
 'Price': '$7500',
 'Title': '2013 Yamaha FJR 1300',
 'Url': 'https://asheville.craigslist.org/mcd/d/2013-yamaha-fjr-1300/6513320993.html',
 '_id': {'$oid': '5a96dbee6f9ca5410cc9ed98'}}

In [254]:
# Creating subset of keys for FB items
wanted_keys_fb = ['Title', 'Location', 'Price', 'Description', 'Url'] 

# creating subset of keys for LG and CL items
wanted_keys = wanted_keys_fb + ['Latitude', 'Longitude']

def clean_up_list_of_dicts(raw_list):
    '''
    This file cleans up a raw list of items and writes them to a text file.
    '''
    
    if raw_list == fb_used_items_raw:
        with open('fb_used_items_filtered.txt', 'w+') as file:
            for item in raw_list:
                for k in wanted_keys_fb:
                    lines = item[k].split()
                    split_lines = [line.replace('\n', '').strip() for line in lines]
                    file.write("{}".format(' '.join(split_lines)) + '\t')
                file.write('\n')
            
    elif raw_list == lg_used_items_raw:
        with open('lg_used_items_filtered.txt', 'w+') as file:
            for item in raw_list:
                for k in wanted_keys:
                    lines = str(item[k]).split()
                    split_lines = [line for line in lines if line.strip()]            
                    file.write("{}".format(' '.join(split_lines)) + '\t')
                file.write('\n')
                
    else:
        with open('cl_used_items_filtered.txt', 'w+') as file:
            for item in raw_list:
                for k in wanted_keys:
                    if k == 'Description':
                        lines = str(''.join(item[k])).split()
                        split_lines = [line.replace('\n', '').strip() for line in lines]
                        split_lines = ' '.join(split_lines)
                        file.write(split_lines + '\t')
                    else:
                        lines = str(item[k]).split()
                        split_lines = [line.replace('\n', '').strip() for line in lines]
                        file.write("{}".format(' '.join(split_lines)) + '\t')
                file.write('\n')
    
    file.close()

In [255]:
clean_up_list_of_dicts(fb_used_items_raw)
clean_up_list_of_dicts(lg_used_items_raw)
clean_up_list_of_dicts(cl_used_items_raw)

## Facebook Used Items

In [256]:
#saving filtered data to pandas dataframe
fb_items_df = pd.read_csv('fb_used_items_filtered.txt', delimiter='\t', names=wanted_keys_fb, usecols=wanted_keys_fb)

fb_items_df.head()

,Title,Location,Price,Description,Url
0,Traier,"Forest City, NC",FREE,I am looking to trade for a good lawnmower trailer... this trailer has no title well built home made can take to DMV to get a title if you want to..... 2 tires are bad and no ramps,https://www.facebook.com/marketplace/item/150586762282415
1,Couch,"Arden, NC",$150,In pretty good condition cushion on the right needs a little added support but still a great couch.,https://www.facebook.com/marketplace/item/196408301114608
2,AMAZING BRAND NEW MATTRESS AND BOX SPRINGS ON CLEARANCE! TAKE IT HOME TODAY FOR ONLY $40 DOWN!,"Fletcher, NC",$40,"$40 DOWN TODAY, TAKE HOME NOW! THEN PAY OFF WITH YOUR REFUND! Don’t pay retail prices for a luxury mattress! Come by and see for yourself today. Up to 50% to 80% off big box store pricing! Completely brand new in plastic! Delivery is available. $40 Down Today and sleep in your new bed tonight!!! LUXURY SETS 50-80% OFF - GOING FAST! Supplies Limited! FIRST COME, FIRST SERVED! Everything is brand new, with full warranty and priced to sell. All mattress sizes and types available including pillo...",https://www.facebook.com/marketplace/item/209952722918617
3,Theater chairs $30 for all!!!,"Asheville, NC",$30,You can clearly see the scratches but still very comfy chairs. All four for 30.,https://www.facebook.com/marketplace/item/155349635165246
4,Sofa with double recliner,"Asheville, NC",$150,You can see the scratches on the side but still a great couch.,https://www.facebook.com/marketplace/item/170421897071508

In [257]:
fb_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2737 entries, 0 to 2736
Data columns (total 5 columns):
Title          2485 non-null object
Location       2484 non-null object
Price          2324 non-null object
Description    247 non-null object
Url            2737 non-null object
dtypes: object(5)
memory usage: 107.0+ KB

In [258]:
#dropping duplicates
fb_items_df.drop_duplicates(subset=['Title', 'Location', 'Price'],inplace=True)
#resetting index
fb_items_df.reset_index(inplace=True, drop=True)

len(fb_items_df)

2463

In [259]:
fb_items_df['Price'].unique()

array(['FREE', '$150', '$40', '$30', '$60', '$800', '$20', '$18', '$115',
       '$75', '$1', '$50', '$15 – $20', '$225', '$100', '$95', '$200',
       '$80', '$4', '$300', '$5', '$70', '$585', '$181', '$325', '$10',
       '$35', 'RM10', '$400', '$25', '$125', '$1,409', '$180', '$2,800',
       '$700', '$350', '$45', '$2', nan, '$500', '$126', '$675', '$175',
       '$15', '$1,000', '$135', '$299', '$169', '$36', '$85', '$450',
       '$950', '$12', '$999', '$39', '$1,080', '$131', '$120', '$65',
       '$185', '$245', '$260', '$112', '$250', '$1,350', '$5,100', '$160',
       '$157', '$81', '$3', '$162', '$197', '$174', '$90', '$5,999',
       '$240', '$19', '$119', '$55', 'RM50', '$3,500', '$94', '$1,500',
       '$99', '$182', '$110', '$1,900', '$190', '$11', '$8', '$195',
       '$270', '$54', '$375', '₹40', '$140', '$32', '$2,750', '$243',
       '₹25', '$1,400', '$106', '$221', '$154', '$111', '$143', '$2,200',
       '$137', '$3,195', '$900', '$535', '$648', '$550', '$390', '$9',
       '$399', '$173', '$1,200', '$5 – 5150', '$1,100', '$10 –1020',
       '$5,285', '$600', '$3,000', '$10 –1012', '$7', '$42', '$11,111',
       '$121', '$51', '$650', '₫12', '$249', '$290', '$275', '$350 350400',
       '$225 225250', '$130', '$575', '$82', '$108', '$22', '$499', '$235',
       '$16', '$199', '$424', '$295', '$850', '$21', '$495', '$31', '$149',
       '$40 –4050', '$105', '$360', '$123,456', '$27', '$364', '$315',
       '$139', '$38', '$6', '$1,234', '$13 –1340', '$28', '$76', '$24',
       '$405', '$37', '$6 – 68', '$26', '$64', '$3 – 3250', '$799', '$14',
       '$48', '$103', '$13', '$145', '$2,000', '$1,250', '$1,278', '$52',
       '$118', '$1,025', '$2,250', '$7,800', '$1,377', '$6,500', '$8,500',
       '$2,925', '$3,700', '$5,500', '$4,200', '$5,000', '$2,300',
       '$3,200', '$2,880', '$6,300', '$8,995', '$4,000', '$5,800', '$975',
       '$6,000', '$3,695', '$5,950', '$4,600', '$13,900', '$13,950',
       '$7,000', '$5,250', '$9,500', '$6,900', '$2,500', '$16,200',
       '$4,500', '$874', '$11,900', '$5,600', '$1,672', '$13,500',
       '$3,250', '$3,420', '$1,800', '$2,655', '$13,450', '$7,900', '$922',
       '$607', '$1,600', '$4,230', '$3,995', '$2,995', '$5,450', '$8,495',
       '$10,950', '$3,295', '$8,895', '$10,000', '$5,995', '$7,600',
       '$3,750', '$2,475', '$1,750', '$9,900', '$1,300', '$750', '$5,350',
       '$7,500', '$3,645', '$13,770', '$4,132', '$4,650', '$3,600',
       '$33,900', '$3,870', '$4,950', '$3,950', '$21,000', '$8,000',
       '$7,200', '$3,495', '$1,700', '$1,935', '$425', '$12,000', '$9,800',
       '$26,000', '$9,000', '$8,200', '$202', '$2,350', '$17,000',
       '$10,500', '$39,000', '$100,000', '$123,456,789', '$34,228', '$72',
       '$15,600', '$43', '$38,000', '$2,700', '$4,050', '$8,800', '$9,200',
       '$9,700', '$14,900', '$9,499', '$163', '$49,800', '$540', '$53',
       '$150 150200', '$17', '$30 –3050', '$80 –80120', '$89', '$153',
       '$1 – 110', '$30,000', '$7 – 715', '$3 – 35', '$230', '$58'], dtype=object)

In [260]:
#converting free items to 0
fb_items_df['Price'] = fb_items_df['Price'].str.replace('FREE', '0')

#removing extraneous characters from price column 
fb_items_df['Price'].replace("[$,₫₹]",'',regex=True, inplace=True)

In [261]:
#lengths of empty value items 
print(len(fb_items_df[fb_items_df['Title'].isnull()]))
print(len(fb_items_df[fb_items_df['Price'].isnull()]))

fb_items_df[fb_items_df['Title'].isnull()]

3
162

,Title,Location,Price,Description,Url
87,NaN,NaN,NaN,NaN,https://www.facebook.com/marketplace/item/186722308759905
301,NaN,NaN,25,NaN,https://www.facebook.com/marketplace/item/148555965818363
1742,NaN,NaN,8500,NaN,https://www.facebook.com/marketplace/item/172699836674399

In [262]:
#dropping rows with no title or price
fb_items_df.dropna(axis=0,subset=['Title', 'Price'],inplace=True)

#resetting index
fb_items_df.reset_index(inplace=True, drop=True)

#printing items with prices that contain hyphens
print(fb_items_df[fb_items_df['Price'].str.contains('–')]['Url'])
fb_items_df[fb_items_df['Price'].str.contains('–')]

21       https://www.facebook.com/marketplace/item/340461016472208
578      https://www.facebook.com/marketplace/item/261864411014387
605     https://www.facebook.com/marketplace/item/1853315894692178
669      https://www.facebook.com/marketplace/item/169623957155463
901     https://www.facebook.com/marketplace/item/1752600715047257
1007     https://www.facebook.com/marketplace/item/186428238786388
1141    https://www.facebook.com/marketplace/item/1926259530782131
1192    https://www.facebook.com/marketplace/item/2020026174910595
1858     https://www.facebook.com/marketplace/item/390634241400999
1876    https://www.facebook.com/marketplace/item/1509510042498236
2058    https://www.facebook.com/marketplace/item/2038177213137722
2138     https://www.facebook.com/marketplace/item/191076374822423
2147     https://www.facebook.com/marketplace/item/148877439160291
Name: Url, dtype: object

,Title,Location,Price,Description,Url
21,Furnitures,"Clyde, NC",15 – 20,Long dresser 15 small 5 table and two chairs 15 all used but in good condition thanks so much,https://www.facebook.com/marketplace/item/340461016472208
578,Leather sale more added to the pile.,"Asheville, NC",5 – 5150,NaN,https://www.facebook.com/marketplace/item/261864411014387
605,Snake skins,"Asheville, NC",10 –1020,NaN,https://www.facebook.com/marketplace/item/1853315894692178
669,Infant Rompers,"Forest City, NC",10 –1012,NaN,https://www.facebook.com/marketplace/item/169623957155463
901,Two canon pixma printers,"Brevard, NC",40 –4050,NaN,https://www.facebook.com/marketplace/item/1752600715047257
1007,MyCharge AmpProng Powerbank,"Hendersonville, NC",13 –1340,NaN,https://www.facebook.com/marketplace/item/186428238786388
1141,Never Opened Blurays and Dvd,"Waynesville, NC",6 – 68,NaN,https://www.facebook.com/marketplace/item/1926259530782131
1192,DVDs stacked to the ceiling!! Also the lady that asked for Jack black movies message me again,"Waynesville, NC",3 – 3250,NaN,https://www.facebook.com/marketplace/item/2020026174910595
1858,Chaps large to xlarge 2x both pair is lined,"Canton, NC",30 –3050,NaN,https://www.facebook.com/marketplace/item/390634241400999
1876,Designer belts,"Asheville, NC",80 –80120,NaN,https://www.facebook.com/marketplace/item/1509510042498236
2058,bracelets,"Leicester, NC",1 – 110,NaN,https://www.facebook.com/marketplace/item/2038177213137722
2138,flower crown,"Leicester, NC",7 – 715,NaN,https://www.facebook.com/marketplace/item/191076374822423
2147,Old Navy youth medium hoodie thin material,"Weaverville, NC",3 – 35,NaN,https://www.facebook.com/marketplace/item/148877439160291

In [263]:
fb_items_df[fb_items_df['Price'].str.match('150 150200')].index

Int64Index([1823], dtype='int64')

In [264]:
#adjusting price discrepencies
indexes = fb_items_df[fb_items_df['Price'].str.contains('–')].index
price_changes = ['20','150','20','10','50','10','8','250','50','120','10','15','5']
for index,price in zip(indexes,price_changes):
    fb_items_df.iloc[index,2] = price

#adjusting further price discrepencies
print(fb_items_df[fb_items_df['Price'] == '150 150200'])
print(fb_items_df[fb_items_df['Price'] == '225 225250'])
print(fb_items_df[fb_items_df['Price'] == '350 350400'])

fb_items_df.iloc[fb_items_df[fb_items_df['Price'].str.match('150 150200')].index,2] = '200'
fb_items_df.iloc[fb_items_df[fb_items_df['Price'].str.match('225 225250')].index,2] = '200'
fb_items_df.iloc[fb_items_df[fb_items_df['Price'].str.match('350 350400')].index,2] = '400'

print(fb_items_df[fb_items_df['Price'] == 'RM50'])
print(fb_items_df[fb_items_df['Price'] == 'RM10'])

fb_items_df.iloc[fb_items_df[fb_items_df['Price'].str.match('RM50')].index,2] = '50'
fb_items_df.iloc[fb_items_df[fb_items_df['Price'].str.match('RM10')].index,2] = '10'

#converting price column to float
fb_items_df['Price'] = fb_items_df['Price'].astype(float)

      Title       Location       Price Description  \
1823  Shoes  Asheville, NC  150 150200         NaN

                                                             Url
1823  https://www.facebook.com/marketplace/item/1981755991838863
                       Title         Location       Price Description  \
759  Beats studio 3 wireless  Weaverville, NC  225 225250         NaN

                                                           Url
759  https://www.facebook.com/marketplace/item/710006912521411
                               Title       Location       Price Description  \
749  Lenovo Core i5 Desktop Computer  Asheville, NC  350 350400         NaN

                                                            Url
749  https://www.facebook.com/marketplace/item/1895313074050705
                                                   Title      Location Price  \
272  Household itemstable with four chairs in good shape  Old Fort, NC  RM50
995                                           DVD player  Old Fort, NC  RM50

    Description                                                        Url
272         NaN  https://www.facebook.com/marketplace/item/175419806515622
995         NaN  https://www.facebook.com/marketplace/item/247786625762468
       Title      Location Price  \
54  Area rug  Old Fort, NC  RM10

                                                                                      Description  \
54  This area rug is indecent shape no holes or stains..10.00 and it yours contact Tina 6681597..

                                                          Url
54  https://www.facebook.com/marketplace/item/890455404467674

In [265]:
#finding max values of price for fb dataframe, more typos
fb_items_df.sort_values('Price', ascending=False)[:5]

,Title,Location,Price,Description,Url
1687,Front clip for expedition,"Asheville, NC",123456789.0,NaN,https://www.facebook.com/marketplace/item/910827172430442
1773,1994 Toyota Pickup,"Marshall, NC",123456789.0,NaN,https://www.facebook.com/marketplace/item/1787021261369590
930,Parts from a 55” Sharp Flatscreen TV,"Fletcher, NC",123456.0,NaN,https://www.facebook.com/marketplace/item/2118734685021249
1333,Magazine and two 8×10 poster card picture,"Asheville, NC",123456.0,NaN,https://www.facebook.com/marketplace/item/1822458531379836
1681,ISO* Dana 21 transfer case,"Landrum, SC",100000.0,NaN,https://www.facebook.com/marketplace/item/1796263684013180

In [266]:
#extracting indexes of highest priced items, all mispriced
indexes = fb_items_df.sort_values('Price', ascending=False)[:5].index

#changing them to null values -- cant change to 0 since those are already designated for free items
fb_items_df.iloc[indexes, 2] = None

#more accurate highest priced items
fb_items_df.sort_values('Price', ascending=False)[:5]

,Title,Location,Price,Description,Url
1775,New F-150 FREE YETI COOLER,"Maggie Valley, NC",49800.0,NaN,https://www.facebook.com/marketplace/item/223396668235254
1655,2017 Jeep Wrangler,"Hendersonville, NC",39000.0,NaN,https://www.facebook.com/marketplace/item/506764806385188
1719,2017 Toyota Tacoma Double Cab V6 4WD,"Old Fort, NC",38000.0,NaN,https://www.facebook.com/marketplace/item/889590744548463
1689,2016 Jeep Wrangler Unlimited,"Waynesville, NC",34228.0,NaN,https://www.facebook.com/marketplace/item/176734523098659
1591,2016 Chevrolet Colorado,"Hendersonville, NC",33900.0,NaN,https://www.facebook.com/marketplace/item/1317788615033137

In [267]:
fb_items_df['Location'].unique()

array(['Forest City, NC', 'Arden, NC', 'Fletcher, NC', 'Asheville, NC',
       'Nebo, NC', 'Campobello, SC', 'Candler, NC', 'Old Fort, NC',
       'Mills River, NC', 'Marion, NC', 'Leicester, NC', 'Waynesville, NC',
       'Black Mountain, NC', 'Clyde, NC', 'Flat Rock, NC', 'Fairview, NC',
       'Burnsville, NC', 'Travelers Rest, SC', 'Rutherfordton, NC',
       'Swannanoa, NC', 'Marietta, SC', 'Hendersonville, NC',
       'Brevard, NC', 'Saluda, NC', 'Weaverville, NC', 'Spindale, NC',
       'Canton, NC', 'Landrum, SC', 'Green Mountain, NC', 'Del Rio, TN',
       'Spruce Pine, NC', 'Columbus, NC', 'Cherokee, NC',
       'Pisgah Forest, NC', 'Bakersville, NC', 'Mars Hill, NC',
       'Lake Toxaway, NC', 'Marshall, NC', 'Alexander, NC',
       'Maggie Valley, NC', 'Etowah, NC', 'Lake Lure, NC',
       'East Flat Rock, NC', 'Horse Shoe, NC', 'Inman, SC',
       'Barnardsville, NC', 'Tryon, NC', 'Greer, SC', 'Mill Spring, NC',
       'Greeneville, TN', 'Cleveland, SC', 'Union Mills, NC',
       'Taylors, SC', 'Tuckasegee, NC', 'Hollywood, FL', 'Hot Springs, NC',
       'Erwin, TN', 'Pickens, SC', 'Gerton, NC', 'Zirconia, NC'], dtype=object)

In [268]:
#dropping item with a location in FL
print(fb_items_df[fb_items_df.Location == 'Hollywood, FL'])

fb_items_df.drop(1620,inplace=True)
fb_items_df.reset_index(inplace=True, drop=True)

                     Title       Location   Price Description  \
1618  2000 Ford expedition  Hollywood, FL  5500.0         NaN

                                                            Url
1618  https://www.facebook.com/marketplace/item/834995816703621

In [269]:
#checking for any remaining duplicates
print(fb_items_df[fb_items_df.duplicated(subset=['Title','Price','Location'], keep=False)])

fb_items_df.info()

Empty DataFrame
Columns: [Title, Location, Price, Description, Url]
Index: []
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2298 entries, 0 to 2297
Data columns (total 5 columns):
Title          2298 non-null object
Location       2298 non-null object
Price          2293 non-null float64
Description    245 non-null object
Url            2298 non-null object
dtypes: float64(1), object(4)
memory usage: 89.8+ KB

In [270]:
fb_items_df.head()

,Title,Location,Price,Description,Url
0,Traier,"Forest City, NC",0.0,I am looking to trade for a good lawnmower trailer... this trailer has no title well built home made can take to DMV to get a title if you want to..... 2 tires are bad and no ramps,https://www.facebook.com/marketplace/item/150586762282415
1,Couch,"Arden, NC",150.0,In pretty good condition cushion on the right needs a little added support but still a great couch.,https://www.facebook.com/marketplace/item/196408301114608
2,AMAZING BRAND NEW MATTRESS AND BOX SPRINGS ON CLEARANCE! TAKE IT HOME TODAY FOR ONLY $40 DOWN!,"Fletcher, NC",40.0,"$40 DOWN TODAY, TAKE HOME NOW! THEN PAY OFF WITH YOUR REFUND! Don’t pay retail prices for a luxury mattress! Come by and see for yourself today. Up to 50% to 80% off big box store pricing! Completely brand new in plastic! Delivery is available. $40 Down Today and sleep in your new bed tonight!!! LUXURY SETS 50-80% OFF - GOING FAST! Supplies Limited! FIRST COME, FIRST SERVED! Everything is brand new, with full warranty and priced to sell. All mattress sizes and types available including pillo...",https://www.facebook.com/marketplace/item/209952722918617
3,Theater chairs $30 for all!!!,"Asheville, NC",30.0,You can clearly see the scratches but still very comfy chairs. All four for 30.,https://www.facebook.com/marketplace/item/155349635165246
4,Sofa with double recliner,"Asheville, NC",150.0,You can see the scratches on the side but still a great couch.,https://www.facebook.com/marketplace/item/170421897071508

## Letgo Items

In [271]:
lg_items_df = pd.read_csv('lg_used_items_filtered.txt', delimiter='\t', names=wanted_keys, usecols=wanted_keys)

lg_items_df.head()

,Title,Location,Price,Description,Url,Latitude,Longitude
0,brown wooden console table,Canton,200.0,NaN,https://us.letgo.com/en/i/brown-wooden-console-table_d493fd46-f892-4a31-85bb-e66f089714ba,35.462248,-82.864510
1,Chevrolet - Astro - 1994,Canton,1400.0,"94 Chevy Astro Van,..208,000 miles..Runs and drives great...Almost new Mud and snow tires..This will make a great work van...I just had the fuel injection replaced which cost me $360 but van runs as nd sound great....CONTACT 828593O11O Call or Text",https://us.letgo.com/en/i/Chevrolet-Astro-1994_3222e597-0816-4743-bba6-ad9c0ad7fc17,35.536222,-82.809232
2,54 Inch Light Bar,Canton,80.0,54 Inch Light Bar...New never been installed...Call or Text [TL_HIDDEN],https://us.letgo.com/en/i/54-Inch-Light-Bar_fbe7f2b2-29b4-4a39-a1c6-77e8fde56ab5,35.536222,-82.809232
3,Jr Tour Golf Clubs,Leicester,40.0,Right handed golf clubs,https://us.letgo.com/en/i/Jr-Tour-Golf-Clubs_40324f63-3b18-401a-bdad-900d58fa9be1,35.657393,-82.705152
4,Glass vase,Asheville,80.0,NaN,https://us.letgo.com/en/i/Glass-vase_ebaad5f6-afc0-42cb-99b2-aae9ce0cec31,35.580766,-82.622581

In [272]:
lg_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
Title          4998 non-null object
Location       5000 non-null object
Price          5000 non-null float64
Description    4267 non-null object
Url            5000 non-null object
Latitude       5000 non-null float64
Longitude      5000 non-null float64
dtypes: float64(3), object(4)
memory usage: 273.5+ KB

In [273]:
lg_items_df.drop_duplicates(subset=['Title', 'Location', 'Price'],inplace=True)
lg_items_df.reset_index(inplace=True, drop=True)

print(len(lg_items_df))

lg_items_df[lg_items_df['Title'].isnull()]

4839

,Title,Location,Price,Description,Url,Latitude,Longitude
605,NaN,Brevard,5.0,NaN,https://us.letgo.com/en/i/_dbaf1640-d340-4bd0-9c6b-39c3f76372f9,35.235191,-82.736244
3863,NaN,Alexander,20.0,NaN,https://us.letgo.com/en/i/-_666dde4f-c9ea-42d9-a513-294767398a6c,35.676406,-82.630720

In [274]:
#removing items missing a title
lg_items_df.drop(605,inplace=True)
lg_items_df.drop(3863,inplace=True)
lg_items_df.reset_index(inplace=True, drop=True)

#quick glance as highest priced items
lg_items_df.sort_values('Price',ascending=False)[:5]

,Title,Location,Price,Description,Url,Latitude,Longitude
4160,Used tires located in Waynesville,Waynesville,123456792.0,Used tires located in waynesville . I have around 200 different tires ask about sizes . [TL_HIDDEN],https://us.letgo.com/en/i/Used-tires-located-in-Waynesville_793ddbad-cf13-4305-b187-533d2bdded6d,35.524277,-82.987367
2026,HOUSE For sale 4+BR 3BA,Hendersonville,380000.0,NaN,https://us.letgo.com/en/i/HOUSE-For-sale-4-BR-3BA_912f1d95-06d6-4d3d-a0ce-51f61c5b308f,35.364368,-82.485275
2336,black and blue Bosch corded power tool with case,Candler,123456.0,NaN,https://us.letgo.com/en/i/black-and-blue-Bosch-corded-power-tool-with-case_d53d6b4f-5c34-4926-8acf-0e2124d422e7,35.515500,-82.710921
1832,OTHER For sale 3BR 2BA,Hendersonville,59900.0,"Very nice 3 bedroom 2 bath home in quiet convenient 55 + park. Approximately 2000 sq.ft. Stove, refrigerator, washer and dryer included. You must be 55 years old or older to live in this park In Hendersonville, NC Call Cathy [TL_HIDDEN]",https://us.letgo.com/en/i/OTHER-For-sale-3BR-2BA_0fa4af67-c657-45c4-8e58-9dda96b0a61a,35.291241,-82.449486
4824,Toyota - Tundra - 2010,Clyde,35000.0,"Only 60,000 miles! Comes with off road package with a built in air compressor. To many extras to list the tundra is a platinum edition with heated and cooled seats, back up camera... 10 in lift with racing suspension. No rust as it’s an Arizona truck.",https://us.letgo.com/en/i/Toyota-Tundra-2010_ec3efab0-5cfe-41eb-b8d5-69ffcf899b04,35.533019,-82.907249

In [275]:
#changing items price to None for indeterminate prices and dropping real estate for sale
lg_items_df.iloc[4160,2] = None
lg_items_df.iloc[2336,2] = None
lg_items_df.drop(2026, inplace=True)
lg_items_df.drop(1832, inplace=True)
lg_items_df.reset_index(inplace=True, drop=True)

lg_items_df.sort_values('Price',ascending=False)[:5]

,Title,Location,Price,Description,Url,Latitude,Longitude
4822,Toyota - Tundra - 2010,Clyde,35000.0,"Only 60,000 miles! Comes with off road package with a built in air compressor. To many extras to list the tundra is a platinum edition with heated and cooled seats, back up camera... 10 in lift with racing suspension. No rust as it’s an Arizona truck.",https://us.letgo.com/en/i/Toyota-Tundra-2010_ec3efab0-5cfe-41eb-b8d5-69ffcf899b04,35.533019,-82.907249
2202,White montana rv trailer,Hendersonville,28000.0,"2011, 38' Keystone Montana Mountaineer Bunk House 5th Wheel. 4 slides, outside kitchen, outside shower, all new tires, super clean, 1 1/2 baths, 2 doors, TV included",https://us.letgo.com/en/i/White-montana-rv-trailer_64aa2e73-76a1-4784-a69f-011bddca03d0,35.390200,-82.372500
435,Pontiac - trans am - 1978,Burnsville,23500.0,"Factory mayan red with white interior, Original 400 Pontiac 6.6L, Automatic, Numbers matching with build sheet, w72, extremely nice car!! Totally restored.",https://us.letgo.com/en/i/Pontiac-trans-am-1978_59284572-f18a-4256-8a32-f8ebcbaab766,35.917260,-82.350009
569,OTHER For sale 2BR 2BA,Hendersonville,22500.0,"Nice 2 bedroom 2 bath mobile home. Approximately 780 sq. Ft. Stove, refrigerator, washer and dryer included. $22,500. You must be 55 yrs. old or older to live in this park",https://us.letgo.com/en/i/OTHER-For-sale-2BR-2BA_9141b6f6-e4a4-469a-9dc4-630b273d7c2a,35.291100,-82.449287
2885,Jeep - Wrangler - 2013,Brevard,18500.0,"Sport. Engine in very good condition, maintained regularly. Automatic with running boards, soft top, Uconnect system, Sirius Satellite option, air conditioning, cruse control, hill assist, power windows, fairly new tires. 70,000 miles. KBB price 18,900. Carpet has been removed but there are weather tech mats in its place. Cash only.",https://us.letgo.com/en/i/Jeep-Wrangler-2013_09000ddc-b0ce-4c58-ab96-38459a3372f6,35.200288,-82.755935

In [276]:
#dropping another real estate related item
lg_items_df.drop(569, inplace=True)
lg_items_df.reset_index(inplace=True, drop=True)

lg_items_df.sort_values('Price',ascending=False)[:5]

,Title,Location,Price,Description,Url,Latitude,Longitude
4821,Toyota - Tundra - 2010,Clyde,35000.0,"Only 60,000 miles! Comes with off road package with a built in air compressor. To many extras to list the tundra is a platinum edition with heated and cooled seats, back up camera... 10 in lift with racing suspension. No rust as it’s an Arizona truck.",https://us.letgo.com/en/i/Toyota-Tundra-2010_ec3efab0-5cfe-41eb-b8d5-69ffcf899b04,35.533019,-82.907249
2201,White montana rv trailer,Hendersonville,28000.0,"2011, 38' Keystone Montana Mountaineer Bunk House 5th Wheel. 4 slides, outside kitchen, outside shower, all new tires, super clean, 1 1/2 baths, 2 doors, TV included",https://us.letgo.com/en/i/White-montana-rv-trailer_64aa2e73-76a1-4784-a69f-011bddca03d0,35.390200,-82.372500
435,Pontiac - trans am - 1978,Burnsville,23500.0,"Factory mayan red with white interior, Original 400 Pontiac 6.6L, Automatic, Numbers matching with build sheet, w72, extremely nice car!! Totally restored.",https://us.letgo.com/en/i/Pontiac-trans-am-1978_59284572-f18a-4256-8a32-f8ebcbaab766,35.917260,-82.350009
2884,Jeep - Wrangler - 2013,Brevard,18500.0,"Sport. Engine in very good condition, maintained regularly. Automatic with running boards, soft top, Uconnect system, Sirius Satellite option, air conditioning, cruse control, hill assist, power windows, fairly new tires. 70,000 miles. KBB price 18,900. Carpet has been removed but there are weather tech mats in its place. Cash only.",https://us.letgo.com/en/i/Jeep-Wrangler-2013_09000ddc-b0ce-4c58-ab96-38459a3372f6,35.200288,-82.755935
4215,Dodge - Dart - 1972,Burnsville,15000.0,Small block 360 904 transmission 373 gear runs great runs low 11’s in quarter mile on motor,https://us.letgo.com/en/i/Dodge-Dart-1972_fb2fe840-be39-4339-9fb9-918b44f04551,35.888897,-82.345189

In [277]:
lg_items_df['Location'] = lg_items_df['Location'].str.lower()
lg_items_df['Location'].unique()

array(['canton', 'leicester', 'asheville', 'candler', 'marshall',
       'waynesville', 'fletcher', 'hendersonville', 'old fort',
       'horse shoe', 'woodfin', 'black mountain', 'maggie valley',
       'burnsville', 'weaverville', 'zirconia', 'swannanoa', 'hot springs',
       'arden', 'east flat rock', 'marion', 'mars hill', 'эшвилл',
       'flat rock', 'rutherfordton', 'clyde', 'saluda', 'alexander',
       'fairview', '28804', 'mill spring', 'brevard', 'mills river',
       'penrose', 'pisgah forest', 'barnardsville', 'biltmore lake',
       'etowah', 'travelers rest', '28715', 'lake lure', 'montreat',
       'buncombe county', 'haywood county', 'dana', 'biltmore forest',
       'dellwood', 'pisgahforest', 'hendersonville, nc, usa', 'flag pond',
       'asheville, nc, usa', 'laurel park'], dtype=object)

In [278]:
locations_to_change = [('canton', 'canton, nc'), ('leicester', 'leicester, nc'), ('asheville', 'asheville, nc'),
                       ('candler', 'candler, nc'), ('marshall', 'marshall, nc'), ('waynesville', 'waynesville, nc'),
                       ('fletcher', 'fletcher, nc'), ('hendersonville', 'hendersonville, nc'), ('old fort', 'old fort, nc'),
                       ('horse shoe', 'horse shoe, nc'), ('woodfin', 'asheville, nc'), ('black mountain', 'black mountain, nc'),
                       ('maggie valley', 'maggie valley, nc'), ('burnsville', 'burnsville, nc'), ('weaverville', 'weaverville, nc'),
                       ('zirconia', 'zirconia, nc'), ('swannanoa', 'swannanoa, nc'), ('hot springs', 'hot springs, nc'),
                       ('arden', 'arden, nc'), ('east flat rock', 'east flat rock, nc'), ('marion', 'marion, nc'), ('mars hill', 'mars hill, nc'),
                       ('эшвилл', 'asheville, nc'), ('flat rock', 'flat rock, nc'), ('rutherfordton', 'rutherfordton, nc'),
                       ('clyde', 'clyde, nc'), ('saluda', 'saluda, nc'), ('alexander', 'alexander, nc'), ('fairview', 'fairview, nc'),
                       ('28804', 'asheville, nc'), ('mill spring', 'mill spring, nc'), ('brevard', 'brevard, nc'), ('mills river', 'mills river, nc'),
                       ('penrose', 'penrose, nc'), ('pisgah forest', 'pisgah forest, nc'), ('barnardsville', 'barnardsville, nc'),
                       ('biltmore lake', 'candler, nc'), ('etowah', 'etowah, nc'), ('travelers rest', 'travelers rest, sc'), ('28715', 'candler, nc'),
                       ('lake lure', 'lake lure, nc'), ('montreat', 'montreat, nc'), ('buncombe county', 'asheville, nc'), 
                       ('haywood county', 'waynesville, nc'), ('dana', 'dana, nc'), ('biltmore forest', 'asheville, nc'),
                       ('dellwood', 'greenville, sc'), ('pisgahforest', 'pisgah forest, nc'), ('hendersonville, nc, usa', 'hendersonville, nc'),
                       ('flag pond', 'flag pond, tn'), ('asheville, nc, usa', 'asheville, nc'), ('laurel park', 'laurel park, nc')
                      ]

In [279]:
#creating functions to adjust locations. FB df doesn't require any adjustments.
def adjust_location_values(locations_to_change, df):
    if df == 'lg':
        for location in locations_to_change:
            indexes = lg_items_df[lg_items_df['Location'].str.match(re.escape(location[0]))].index
            for index in indexes:
                lg_items_df.iloc[index, 1] = location[1]
        
        lg_items_df['Location'] = lg_items_df['Location'].str.title()
        lg_items_df['Location'] = lg_items_df['Location'].str[:-2] + lg_items_df['Location'].str[-2:].str.upper()
        
    
    else:
        for location in locations_to_change:
            indexes = cl_items_df[cl_items_df['Location'].str.match(re.escape(location[0]))].index
            for index in indexes:
                cl_items_df.iloc[index, 1] = location[1]
        
        cl_items_df['Location'] = cl_items_df['Location'].str.title()
        cl_items_df['Location'].where(cl_items_df['Location'] == 'Unspecified', 
                                      cl_items_df['Location'].str[:-2] + cl_items_df['Location'].str[-2:].str.upper(),
                                     inplace=True)
    
                
def drop_location_values(locations_to_drop, df):
    if df == 'lg':
        for location in locations_to_drop:
            indexes = lg_items_df[lg_items_df['Location'].str.match(re.escape(location))].index
            for index in indexes:
                lg_items_df.drop(index, inplace=True)
            lg_items_df.reset_index(inplace=True, drop=True)
    else:
        for location in locations_to_drop:
            indexes = cl_items_df[cl_items_df['Location'].str.match(re.escape(location))].index
            for index in indexes:
                cl_items_df.drop(index, inplace=True)
            cl_items_df.reset_index(inplace=True, drop=True)

In [280]:
adjust_location_values(locations_to_change, 'lg')

In [281]:
lg_items_df['Location'].unique()

array(['Canton, NC', 'Leicester, NC', 'Asheville, NC', 'Candler, NC',
       'Marshall, NC', 'Waynesville, NC', 'Fletcher, NC',
       'Hendersonville, NC', 'Old Fort, NC', 'Horse Shoe, NC',
       'Black Mountain, NC', 'Maggie Valley, NC', 'Burnsville, NC',
       'Weaverville, NC', 'Zirconia, NC', 'Swannanoa, NC',
       'Hot Springs, NC', 'Arden, NC', 'East Flat Rock, NC', 'Marion, NC',
       'Mars Hill, NC', 'Flat Rock, NC', 'Rutherfordton, NC', 'Clyde, NC',
       'Saluda, NC', 'Alexander, NC', 'Fairview, NC', 'Mill Spring, NC',
       'Brevard, NC', 'Mills River, NC', 'Penrose, NC',
       'Pisgah Forest, NC', 'Barnardsville, NC', 'Etowah, NC',
       'Travelers Rest, SC', 'Lake Lure, NC', 'Montreat, NC', 'Dana, NC',
       'Greenville, SC', 'Flag Pond, TN', 'Laurel Park, NC'], dtype=object)

In [282]:
#checking for any remaining duplicates
print(lg_items_df[lg_items_df.duplicated(subset=['Title','Price','Location'], keep=False)])

#dropping any more remaining duplicates
lg_items_df.drop_duplicates(subset=['Title', 'Location', 'Price'],inplace=True)

#resetting index
lg_items_df.reset_index(inplace=True, drop=True)
lg_items_df[lg_items_df.duplicated(subset=['Title','Price','Location'], keep=False)]

             Title     Location  Price Description  \
4669  Size: Medium  Candler, NC    2.0         NaN
4682  Size: Medium  Candler, NC    2.0         NaN

                                                                              Url  \
4669  https://us.letgo.com/en/i/Size-Medium-_c31faef3-5905-4ee8-87f4-5c415a02acd6
4682   https://us.letgo.com/en/i/Size-Medium_95690609-7745-4e56-aca6-98ccb26a0568

       Latitude  Longitude
4669  35.513503 -82.741074
4682  35.513228 -82.741122

Empty DataFrame
Columns: [Title, Location, Price, Description, Url, Latitude, Longitude]
Index: []

In [283]:
lg_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4833 entries, 0 to 4832
Data columns (total 7 columns):
Title          4833 non-null object
Location       4833 non-null object
Price          4831 non-null float64
Description    4120 non-null object
Url            4833 non-null object
Latitude       4833 non-null float64
Longitude      4833 non-null float64
dtypes: float64(3), object(4)
memory usage: 264.4+ KB

In [284]:
lg_items_df.head()

,Title,Location,Price,Description,Url,Latitude,Longitude
0,brown wooden console table,"Canton, NC",200.0,NaN,https://us.letgo.com/en/i/brown-wooden-console-table_d493fd46-f892-4a31-85bb-e66f089714ba,35.462248,-82.864510
1,Chevrolet - Astro - 1994,"Canton, NC",1400.0,"94 Chevy Astro Van,..208,000 miles..Runs and drives great...Almost new Mud and snow tires..This will make a great work van...I just had the fuel injection replaced which cost me $360 but van runs as nd sound great....CONTACT 828593O11O Call or Text",https://us.letgo.com/en/i/Chevrolet-Astro-1994_3222e597-0816-4743-bba6-ad9c0ad7fc17,35.536222,-82.809232
2,54 Inch Light Bar,"Canton, NC",80.0,54 Inch Light Bar...New never been installed...Call or Text [TL_HIDDEN],https://us.letgo.com/en/i/54-Inch-Light-Bar_fbe7f2b2-29b4-4a39-a1c6-77e8fde56ab5,35.536222,-82.809232
3,Jr Tour Golf Clubs,"Leicester, NC",40.0,Right handed golf clubs,https://us.letgo.com/en/i/Jr-Tour-Golf-Clubs_40324f63-3b18-401a-bdad-900d58fa9be1,35.657393,-82.705152
4,Glass vase,"Asheville, NC",80.0,NaN,https://us.letgo.com/en/i/Glass-vase_ebaad5f6-afc0-42cb-99b2-aae9ce0cec31,35.580766,-82.622581

## Craigslist Items

In [285]:
cl_items_df = pd.read_csv('cl_used_items_filtered.txt', delimiter='\t', names=wanted_keys, usecols=wanted_keys)

cl_items_df.head()

,Title,Location,Price,Description,Url,Latitude,Longitude
0,2013 Yamaha FJR 1300,(Asheville),$7500,"2013 Yamaha FJR 1300 Sport Touring, 4 cylinder, 12.120 miles, silver, cruise control, traction control, ABS brakes, heated hand grips, Two Brothers exhaust, handle bar risers, 6.5 gal. gas tank, adjustable windshield, saddlebags, excellent condition, very clean. $ 7.500 (828) 250-0373 WWW.GREENVALLEYCARS.COM",https://asheville.craigslist.org/mcd/d/2013-yamaha-fjr-1300/6513320993.html,35.599694,-82.628866
1,2014 Honda Accord White 41k,(Cowpens),$10995,"2014 Honda Accord Automatic, White , On Tan, It has Only 41,980 Miles It Has Spoiler, Power Windows, and Mirrors, Tan Cloth Seats, Power Seats, 4 Cylinder, 4 Door, Radio, 6 CD Changer, FM,AM,CD, XM Radio, Bluetooth, Back up Camera, Side and Curtain Air Bag, 16 Inch Factory Wheels with Firestone Great Tires, Tinted Glass, And Much More, Clean On inside, Runs and Drives Like New, Call Me for more info, 864-266-6936 Willing to Negotiate if offer is fair..... honda, bmw, crv, mercedes, ford, maz...",https://asheville.craigslist.org/ctd/d/2014-honda-accord-white-41k/6513312696.html,35.039000,-81.822000
2,Pet Crate,(HENDERSONVILLE),$50,Petmate Pet Porter for large dogs - plastic shell - wire door,https://asheville.craigslist.org/for/d/pet-crate/6513308129.html,35.257061,-82.505744
3,1970's Fender Vibrosonic Amplifier,(Tryon NC),$750,"Vintage 70's Fender Vibrosonic Reverb guitar amplifier. 15"" Fender pro series speaker and uses 6L6 tubes. Great shape!",https://asheville.craigslist.org/msg/d/1970s-fender-vibrosonic/6513308239.html,None,None
4,Poll Parrot and Weatherbird Comics,(Fletcher),$10,Poll Parrot and Weatherbird Comics - all three only $10. Please email if interested.,https://asheville.craigslist.org/clt/d/poll-parrot-and-weatherbird/6500112360.html,None,None

In [286]:
cl_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2909 entries, 0 to 2908
Data columns (total 7 columns):
Title          2909 non-null object
Location       2909 non-null object
Price          2909 non-null object
Description    2869 non-null object
Url            2909 non-null object
Latitude       2909 non-null object
Longitude      2909 non-null object
dtypes: object(7)
memory usage: 159.2+ KB

In [287]:
cl_items_df.drop_duplicates(subset=['Title', 'Location', 'Price'],inplace=True)
cl_items_df.reset_index(inplace=True, drop=True)

len(cl_items_df)

2807

In [288]:
#removing brackets around values from Location column
cl_items_df['Location'].replace('\(|\)', '', regex=True, inplace=True)

cl_items_df['Location'] = cl_items_df['Location'].str.lower()

#cleaning up price column to convert to float type
cl_items_df['Price'] = cl_items_df['Price'].str.replace('$','')

#replacing 'None' with None because 0 already reserved for free items
cl_items_df['Price'].replace('None',None,inplace=True)

cl_items_df['Price'] = cl_items_df['Price'].astype(float)

In [289]:
cl_items_df.sort_values('Price',ascending=False)[:10]

,Title,Location,Price,Description,Url,Latitude,Longitude
564,Furniture Dealer & Warehouse!Antique Furniture Dealer:Best in WNC,the regeneration station,123456789.0,"Looking for the most unique and coolest furniture dealer in WNC? Check out The Regeneration Station! Whatever you are looking for we have it! Antique furniture, unique collectibles, appliances, and much much more!! Want more than that? We have multiple sister companies, Junk Recyclers our junk removal service which also offers moving, and recycling. GarageTRS is Ashevilles premire motorcycle dealership, specializing in dual-sport, vintage, and Harley-Davidson branded motorcycles! Give us a c...",https://asheville.craigslist.org/fud/d/furniture-dealer/6512340952.html,35.572912,-82.525246
2793,WANTED 1968 69 70 71 72 73 74 PLYMOUTH ROAD RUNNER,mooresville,7777777.0,"I am looking to buy a 1968 thru 1974 Plymouth Road Runner Project car. Does not have to be running or driving. Can be just a roller with no drivetrain. Not looking for a finished show car, looking for a project car or a car that has been sitting CA$H WAITING IF THE AD IS STILL UP I AM STILL LOOKING Please send me your name and what year Road Runner you have for sale, also include a phone number I can call you at. Thanks",https://asheville.craigslist.org/cto/d/wantedplymouth-road-runner/6477749450.html,None,None
1588,2000 camry,marion,1234567.0,2000 Toyota Camry in very good shape for it's age no rust no dents or dings has minor flakes and chips here and there nothing major the hood is the worst part about it but it's not terrible the interior is clean has couple spots here new there also it a 1 owner car it's my nanas she bought it brand new needs nothing clean title she just got new tires put on has 140k miles! Text or call prefer text or email 4000 obo trade for newer car or s 10 in as good of shape as this or better can put as ...,https://asheville.craigslist.org/cto/d/2000-camry/6512795147.html,None,None
176,OIL COMPANY,marshall,900000.0,"Owner Needs to Retire! Grosses 3 million plus! Has 5 trucks. Possible some financing. Net income $150,000.00 +. Could be absentee owner run! Metts Business Broker 828-329-8575",https://asheville.craigslist.org/bfd/d/oil-company/6512106718.html,None,None
177,Moving sale,weaverville,900000.0,"Four dinning room chairs prepped to paint. Bedroom furniture 3pc set. Includes dresser, chest and bedside table. Cabinet or book shelf can be used as TV stand, table, microwave and toaster oven. $550.00 for all or will consider selling separate. Call .",https://asheville.craigslist.org/fuo/d/moving-sale/6512102008.html,35.712600,-82.549100
169,RESTAURANT,hendersonville,650000.0,"Owner Retiring! Grossing $800,000.00 +. Breakfast and Lunch. 22 years in operation. Some financing possible. Metts Business Brokers 828-329-8575",https://asheville.craigslist.org/bfd/d/restaurant/6512101274.html,None,None
639,Looking for a iPhone 7 8 or x,asheville,400500.0,Hello I am looking for a iPhone 7 8 or x that is at least 128 gig or more an my price range is between 400-500$ if you have one text me anytime,https://asheville.craigslist.org/mob/d/looking-for-iphone-7-8-or/6512382205.html,35.859700,-82.710500
183,LITE CONSTRUCTION COMPANY,asheville,300000.0,"Owner Retiring! Lite construction company established over 20 years . Grosses $300,000.00+ with profit margin 1/3. Owner will train. Some possible financing. Metts Business Broker 828-329-8575",https://asheville.craigslist.org/bfd/d/lite-construction-company/6512111308.html,None,None
2566,Avon Products,candler,299900.0,Wild Country Bonus Size Roll-On Antiperspirant Deodorant--$1.99 Black Swede Sport Perfume--15.00 Musk Fire--15.00 Wild Country After Shave Conditioner--$4.00 If interested in these,https://asheville.craigslist.org/hsh/d/avon-products/6502780525.html,35.537600,-82.700100
2565,2007 dodge 3500 6 speed 4x4,candler,299900.0,"Have a dodge 3500 in very good shape. Has had the front in rebuilt, new heater core and ac condenser, very clean truck 4x4 call or text for more information new b&w gooseneck hicth with turn over ball",https://asheville.craigslist.org/cto/d/2007-dodgespeed-4x4/6513217227.html,35.537600,-82.700100

In [290]:
#adjusting prices
indexes = [564,1588,177,639,2566,2565]
price_changes = [None,4000,550,500,None,None]

for index,price in zip(indexes,price_changes):    
    cl_items_df.iloc[index,2] = price

#dropping irrelevant items, real estate or business for sale
indexes = [2793,176,169,183]
for index in indexes:
    cl_items_df.drop(index, inplace=True)

cl_items_df.reset_index(inplace=True, drop=True)

cl_items_df.sort_values('Price',ascending=False)[:10]

,Title,Location,Price,Description,Url,Latitude,Longitude
1410,Rocky Mounts Tandem Carrier,hendersonville nc,200150.0,I have 2 Rocky Mounts Rooftop Tandem Carriers. 1 is in perfect newer condition the other works but needs some TLC. Both for $200 or one for $150. Can be used for a single bike to.,https://asheville.craigslist.org/bik/d/rocky-mounts-tandem-carrier/6512691195.html,35.319200,-82.500000
865,Italian Farm to Table located 6 miles from TIEC,columbus,145000.0,"Dear Chef/Entrepreneur/Investor Have you been dreaming about a path to a secure future where your talents and passions can grow and be expressed in a beautiful setting surrounded by your own freshly picked and locally sourced food? Are you dreaming about a business with strong potential to carry you and your creative business ideas into a viable and sustainable future for you and your family, your associates and employees? If so, then..your dream is just a click away. . .check it out and con...",https://asheville.craigslist.org/bfs/d/italian-farm-to-table-located/6505553966.html,35.253200,-82.197100
995,Scenic Lake Toxaway,"lake toxaway, n.c.",80000.0,"Nice .85 acre buildable lot in scenic Lake Toxaway Estates. Walkable to lake with lake rights. Completed perk test. Tranquil surroundings with mature hardwood trees. $80,000 cash or owner will hold mortgage. Grand Greystone Inn reopening this Spring!",https://asheville.craigslist.org/for/d/scenic-lake-toxaway/6512541892.html,35.145100,-82.919100
26,1954 Spartan Imperial Mansion Double-Ender 37 ft,"fairview, n.c.",73000.0,"This professionally restored Spartan Imperial Double-Ender Mansion is ready to furnish. It is in excellent condition. It has new: birch paneling, insulation, wiring plumbing, LED lights, tires and bearings. The new floor is a Vinyl Composite Tile. The refrigerator has been refurbished, with a new paint job and gaskets. This beautiful trailer is a true gem.",https://asheville.craigslist.org/rvs/d/1954-spartan-imperial-mansion/6503890489.html,35.525800,-82.398500
2448,1963 Chevy Impala SS 409 Convt,none,63900.0,"1963 Chevy Impala SS 409 Convertible. Palomar Red,Auto, factory A/C, PS, PB, am/fm radio. Engine and Trans rebuilt, new front end, power disc front brakes auto trunk release...Runs and drives like new. ready for show and go. True SS Orig Arizona car...Check NADA 6 figures",https://asheville.craigslist.org/cto/d/1963-chevy-impala-ss-409-convt/6513166566.html,None,None
527,MASSEY FERGUSEN 4610 TRACTOR WITH ACCESSORIES,chesnee sc,56500.0,"MF 4610 TRACTOR IS ALMOST NEW WITH ONLY 80 HRS. LATE 2016 MODEL STILL UNDER FULL WARRANTY. IS 4 WHEEL DRIVE, 100 HP WITH RADIO AND AIR CONDITIONING. HAS NEVER BEEN IN A FIELD! $56,500.00 INCLUDES A NEW 7' LONG TILLER AND A NEW 10' LONG BUSH HOG, AVAILABLE AT ADDITIONAL COST IS A 4 BOTTOM TURNER PLOW A CHISEL LOW AND A DOUBLE SECTION HIRES. CAN BE SEEN AT HENDERSON BUILDING CENTER 5874 CHENEE HWY CHESNEE SC 29323 MON-FRI 8AM-4PM SAT 8AM-NOON",https://asheville.craigslist.org/grd/d/massey-fergusen-4610-tractor/6490334993.html,35.115229,-81.870745
1510,"2017 F350 4X4 DUALLY. CREW CAB. 14000 MILES, DIESEL ENGINE",tazewell,55000.0,"GORGEOUS BRIGHT RED 2017 4x4 F350 Dually. Diesel engine. Crew cab. Only 14,000 miles. Mint condition. Only 6 months old. Cloth seats , rubber floorboards. Manual door locks and windows. Not electric. Brand new goose neck and spray in bedliner. Running boards. Nice stereo system. Paid $60,000 for truck plus added spray in Bedliner and goose neck hitch. $55000.",https://asheville.craigslist.org/cto/d/2017-f350-4x4-dually-crew/6512754359.html,36.471000,-83.555200
584,FINANCING AVAILABLE / 2008 Hitachi ZX-160 LC,clayton ga,54900.0,"FINANCING AVAILABLE : CALL OR EMAIL ONLY / NO CALLS ON SUNDAY / NO TRADES / SERIOUS INQUIRIES ONLY / VISIT US AT: www.ashe.equipment - River Ashe / 828-284-ate 7 5 to 2008 Hitachi ZX-160LC Excavator / Manual Thumb / 5,500 Hours on Heat and Air / Tight Boom And Turn Table / Under Carriage % / 1 1 Glass is Broken / 1 Minor Valve Leak Being Fixed $54,990 SEE YOUTUBE VIDEO: http://youtu.be/jj_zkhrhR1U SEE SPECS: http://www.ritchiespecs.com/specification?category=Hydraulic%20Excavator&make=HITACH...",https://asheville.craigslist.org/wad/d/financing-available-2008/6500660603.html,None,None
2339,free drop ceiling GRID Pieces,brevard,48500.0,"We have dismantled about 700 square feet of drop ceiling from our basement remodel and are looking for someone who might need it. Pieces to take include many cross beams and main beams. Pieces range from 2' to 12' long. White finish, no tiles. Come pick up! Please call and we can set a time and date to come and get them.",https://asheville.craigslist.org/zip/d/free-drop-ceiling-grid-pieces/6513128800.html,35.220800,-82.740400
2338,2015 Ford F-350,leicester,48500.0,"2015 Ford F-350 lariat. 6.7 powerstroke 4x4 with fx4 package. Black leather interior (heated and ac seats) with nav and Weather tech floor liners. 295/70r17 toyo mt's with 2"" leveling kit and add a leaf in the rear. 75,000 miles. Very clean truck. Truck is deleted with ppei ezlynk and 5"" exhaust. Please call with any questions NO TEXTS AND NO TRADES and I do not need help selling",https://asheville.craigslist.org/cto/d/2015-ford-350/6490180874.html,35.655231,-82.695955

In [291]:
cl_items_df.iloc[1410,2] = 200

# dropping real estate/businesses for sale
cl_items_df.drop(865, inplace=True)
cl_items_df.drop(995, inplace=True)
cl_items_df.drop(26, inplace=True)
cl_items_df.reset_index(inplace=True, drop=True)

cl_items_df.sort_values('Price',ascending=False)[:10]

,Title,Location,Price,Description,Url,Latitude,Longitude
2445,1963 Chevy Impala SS 409 Convt,none,63900.0,"1963 Chevy Impala SS 409 Convertible. Palomar Red,Auto, factory A/C, PS, PB, am/fm radio. Engine and Trans rebuilt, new front end, power disc front brakes auto trunk release...Runs and drives like new. ready for show and go. True SS Orig Arizona car...Check NADA 6 figures",https://asheville.craigslist.org/cto/d/1963-chevy-impala-ss-409-convt/6513166566.html,None,None
526,MASSEY FERGUSEN 4610 TRACTOR WITH ACCESSORIES,chesnee sc,56500.0,"MF 4610 TRACTOR IS ALMOST NEW WITH ONLY 80 HRS. LATE 2016 MODEL STILL UNDER FULL WARRANTY. IS 4 WHEEL DRIVE, 100 HP WITH RADIO AND AIR CONDITIONING. HAS NEVER BEEN IN A FIELD! $56,500.00 INCLUDES A NEW 7' LONG TILLER AND A NEW 10' LONG BUSH HOG, AVAILABLE AT ADDITIONAL COST IS A 4 BOTTOM TURNER PLOW A CHISEL LOW AND A DOUBLE SECTION HIRES. CAN BE SEEN AT HENDERSON BUILDING CENTER 5874 CHENEE HWY CHESNEE SC 29323 MON-FRI 8AM-4PM SAT 8AM-NOON",https://asheville.craigslist.org/grd/d/massey-fergusen-4610-tractor/6490334993.html,35.115229,-81.870745
1507,"2017 F350 4X4 DUALLY. CREW CAB. 14000 MILES, DIESEL ENGINE",tazewell,55000.0,"GORGEOUS BRIGHT RED 2017 4x4 F350 Dually. Diesel engine. Crew cab. Only 14,000 miles. Mint condition. Only 6 months old. Cloth seats , rubber floorboards. Manual door locks and windows. Not electric. Brand new goose neck and spray in bedliner. Running boards. Nice stereo system. Paid $60,000 for truck plus added spray in Bedliner and goose neck hitch. $55000.",https://asheville.craigslist.org/cto/d/2017-f350-4x4-dually-crew/6512754359.html,36.471000,-83.555200
583,FINANCING AVAILABLE / 2008 Hitachi ZX-160 LC,clayton ga,54900.0,"FINANCING AVAILABLE : CALL OR EMAIL ONLY / NO CALLS ON SUNDAY / NO TRADES / SERIOUS INQUIRIES ONLY / VISIT US AT: www.ashe.equipment - River Ashe / 828-284-ate 7 5 to 2008 Hitachi ZX-160LC Excavator / Manual Thumb / 5,500 Hours on Heat and Air / Tight Boom And Turn Table / Under Carriage % / 1 1 Glass is Broken / 1 Minor Valve Leak Being Fixed $54,990 SEE YOUTUBE VIDEO: http://youtu.be/jj_zkhrhR1U SEE SPECS: http://www.ritchiespecs.com/specification?category=Hydraulic%20Excavator&make=HITACH...",https://asheville.craigslist.org/wad/d/financing-available-2008/6500660603.html,None,None
2336,free drop ceiling GRID Pieces,brevard,48500.0,"We have dismantled about 700 square feet of drop ceiling from our basement remodel and are looking for someone who might need it. Pieces to take include many cross beams and main beams. Pieces range from 2' to 12' long. White finish, no tiles. Come pick up! Please call and we can set a time and date to come and get them.",https://asheville.craigslist.org/zip/d/free-drop-ceiling-grid-pieces/6513128800.html,35.220800,-82.740400
2335,2015 Ford F-350,leicester,48500.0,"2015 Ford F-350 lariat. 6.7 powerstroke 4x4 with fx4 package. Black leather interior (heated and ac seats) with nav and Weather tech floor liners. 295/70r17 toyo mt's with 2"" leveling kit and add a leaf in the rear. 75,000 miles. Very clean truck. Truck is deleted with ppei ezlynk and 5"" exhaust. Please call with any questions NO TEXTS AND NO TRADES and I do not need help selling",https://asheville.craigslist.org/cto/d/2015-ford-350/6490180874.html,35.655231,-82.695955
152,2017 Chevrolet Corvette Stingray,spartanburg sc,45500.0,2017 Corvette Singray 240 Miles Excellent - like new condition Automatic Transmission Torch Red Garage Kept Clean Carfax,https://asheville.craigslist.org/cto/d/2017-chevrolet-corvette/6505215892.html,34.864600,-82.021500
191,2017 Ford Transit Wagon 350 HD XLT HANDICAP Converted,none,44000.0,"2017 Ford Transit Wagon 350 HD XLT High Roof w/Extended Length that has been converted for a wheelchair. Family bought for my dad before he barely had a chance to use it. We bought it at 49,750 and the conversion was another 15,000 Any questions or pics of the vehicle call/txt",https://asheville.craigslist.org/cto/d/2017-ford-transit-wagon-350/6487265028.html,35.586410,-82.556076
1223,PRIME COMMERCIAL UNRESTRICTED PROPERTY,polk county nc,42500.0,"1.72 acre Prime Commerical Property for sale by owner, location hwy 9 polk conty NC. Dual drive, main drive already graveled with side drainage rocks, nice and wide, cleared and leveled on top. This area is a growing commercial area.",https://asheville.craigslist.org/bfs/d/prime-commercial-unrestricted/6512640168.html,35.446400,-82.175200
1645,1967 Chevy II Nova sleeper 600hp 4-speed!!,candler,42500.0,Gonna sell my Chevy II. It has All its original sheetmetal and is laser straight. The car has been painted for 15 years so there are no surprises straight and slick paint. The drivetrain consist of a new 422 ci Small block with Forged eagle internals. AFR Aluminum heads etc. Dyno 597 hp. with All ARP fasteners.( I have all receipts for build).Has a New M22 Rockcrusher 4-speed with Hurst shifter and a New Moser 9 inch reared with a 3:70 gear with auburn posi that has been narrowed 1inch on ea...,https://asheville.craigslist.org/cto/d/1967-chevy-ii-nova-sleeper/6493886811.html,None,None

In [292]:
cl_items_df.Location.unique()

array(['asheville', 'cowpens', 'hendersonville', 'tryon nc', 'fletcher',
       'franklin nc', 'subaru forester', 'none', 'burnsville', 'flat rock',
       'fairview', 'greeneville, tn', 'weaverville', 'mills river',
       'lake junaluska location', 'bristol tn', 'calhoun, ga.', 'canton',
       "alan's jewelry & pawn cherokee", 'bostic, nc', 'sweet',
       'horse shoe', 'reynolds', 'marion',
       'we finance all types of credit!', 'waynesville/clyde/canton',
       '2314 asheville hwy', 'candler', 'brevard',
       'hendersonville/ etowah', 'hendersonville, nc', 'highlands, nc',
       'west asheville', 'any', 'asheville nc', 'knoxville,tn',
       'cocke county,tn', 'greenville', 'asheville, nc', 'rutherfordton',
       'hickory, nc', 'rutherfordton nc', 'great selection!', 'swannanoa',
       'buy here pay here w/ credit reporting!!!', '_kia_ _soul_ _wagon_',
       '_jeep_ _wrangler unlimited_ _suv_', 'spartanburg sc', 'jonesville',
       'gaffney,sc', 'randleman', 'clyde', 'tryon,nc', 'burnsville nc',
       'canton nc', 'weaverville nc', 'maryville, tn', 'rutledge,tn',
       'morganton', 'lake lure marine', 'sylva', 'mars hill',
       'dawsonville, ga.', 'waynesville', 'arden', 's. asheville',
       'chadbourn nc', 'taylors', 'the regeneration station', 'oakley',
       'vintage dreams trading co. booth#246 trs',
       '3635 e independence blvd', 'fletcher/mountain home',
       'black mountain', 'antique tobacco barn', 'north asheville',
       'hickory', 'n. asheville', 'leicester', 'franklin', 'hville',
       'morristown tn', 'talbott', 'sc', 'harmony', 'knoxville',
       'east asheville', 'e asheville/swannanoa',
       'the village antique & decor sevierville', 'newland', 'candler, nc',
       'asheville biltmore', 'kodak', 'marshall nc', 'sylva, nc',
       'edneyville', 'greenville sc', 'east morristown / russellville',
       'marshall', 'forest city nc', 'greensboro', 'spruce pine', 'shelby',
       'leicester area', 'barnardsville', 'lake lure',
       'burnsville/mars hill', 'fletcher/fairview', 'tazewell tn',
       '19 ella lane', 'bakersville', 'mountain home', 'stock#p6155',
       'stock#210816', 'hendersonville,nc', 'gaffney', 'n.e. georgia',
       'chesnee sc', 'spartanburg', 'pineville nc', 'sweeten creek road',
       'elizabethton, tn', 'oteen', 'sc/nc', 'liberty', 'liberty sc',
       'simpsonville', 'biltmore', 'mars hill, nc', 'boone nc',
       'sc lancaster', 'clayton ga', 'dt avl', '_nissan_ _quest_ _van_',
       'sweeten creek antiques', 'old fort', 'oldfort',
       '_chrysler_ _300-series_ _sedan_', 'forest city, nc', 'bat cave',
       'burnsville n.c.', '_dodge_ _dart_ _sedan_', 'johnson city',
       '_ford_ _edge_ _suv_', '_ford_ _f-150_ _truck_',
       'hendersonville/flatrock', '_jeep_ _compass_ _suv_',
       '_ram_ _cargo van_ _van_',
       '_ford_ _super duty f-350 drw chassis cab', 'colorado',
       'bryson city', 'henderson', 'hendersonville nc',
       '_ford_ _escape_ _suv_', '_dodge_ _charger_ _sedan_',
       'fayetteville', 'charleston sc', 'grayson ga', 'fairview nc',
       'murphy', 'inman sc', 'alexander', 'arden nc', 'franklin, nc',
       'south asheville', 'arden, nc', 'nc, sc, ga, tn', 'inman, sc',
       'douglas, ga', 'columbus', 'columbus nc', 'menagerie mercantile',
       'asheville,n.c.', 'glenville', 'asheville/fairview, nc',
       'asheville n.c.', 'southeast asheville, nc', 'weaverville, nc',
       'easley', '501 willard st - durham nc', 'black mountain, nc',
       'marshill', 'marian', 'food lion skatepark', 'mill spring',
       'charlotte,n.c.', 'bevard', 'clinton tn', 'blk. mtn.', 'piedmont',
       'hot springs, nc', 'upstate, sc', '49 mount carmel road',
       'flat rock nc', 'swannaoa', 'bakersville, nc',
       '*2013* *dodge* *ram* *1500* *regular* *cab* *hfe*',
       '*2006* *nissan* *altima* *2.5s* *sedan* *special*',
       '*2013* *dodge* *ram* *1500* *quad* *cab* *2wd* *sl',
       '*2010* *chevrolet* *silverado* *1500* *crew* *cab*',
       '*2006* *ford* *f-350* *sd* *crew* *cab* *lariat* *',
       '*2014* *ford* *f-150* *supercrew* *4x4* *fx4* *roc',
       '*2014* *chrysler* *town* *&* *country* *touring* *',
       '*2012* *gmc* *sierra* *1500* *crew* *cab* *4x4* *z', 'waxhaw',
       '*2012* *toyota* *tacoma* *prerunner* *double* *cab',
       'mills river, nc', 'downtown asheville', 'lafollette',
       'south of forrest city', 'asheville , n c', 'asheville n c',
       'asheville, n c', 'marion nc', 'cashiers', 'west asheville/candler',
       'flat creek / weaverville', 'boone', 'bon vivant, asheville, nc',
       'etowah', 'east asheville nc haw creek', 'sylva n.c.', 'nebo',
       'greensboro, nc', 'yadkinville, nc', 'henderson, nc',
       'asheville,nc', 'toccoa', 'monroe', 'charleston', 'the orange peel',
       'asheville & surrounding area', 'boiling springs sc',
       'drexel/morganton', 'lake james family campground',
       'fairview/fletchet', 'cornelia', 'sevierville',
       'n. asheville-common ground', '539 new leicester hwy',
       'lake lure, nc', 'weaverville n.c', 'w n.c weaverville',
       'asheville n.c', 'sparta nc', 'cherokee', 'whittier',
       '27284_we_finance', 'harriman', 'ashevile',
       'hendersonville/horse shoe', 'oakley, asheville',
       'south asheville/fletcher', 'limestone tn', 'limestone, tn',
       'freeburg pianos', 'calhoun ga', 'avl', 'haywood', 'polk county nc',
       'clinton, knoxville', 'bristol', 'alexander nc', 'hot springs',
       'canton, nc', 'kingsport tn', 'whittier nc', 'black mt/asheville',
       'laurel hill, nc', 'ashville', 'bostic', 'waynesville, nc',
       'asheville / canton', 'sannanowa', 'andrews, nc',
       'boiling spring .sc', 's carolina', 'cullowhee', 'clover',
       'waynesvile, nc', 'wnc', 'west buncombe', 'spartanburg, sc',
       '71 belmont ave', 'henderson county', 'bent creek', 's avl',
       'upstate sc', 'brevard nc', 'we_finance_27284', 'greeneville tn',
       'maggie valley', "harrah's cherokee", 'asheboro',
       'greeneville honda 730 west andrew johnso',
       '_chevrolet_ _suburban_ _suv_', 'hiawasssee, ga',
       '_dodge_ _grand caravan_ _van_', '_nissan_ _rogue_ _suv_',
       'hagen drive', 'pigeon forge', '_jeep_ _grand cherokee_ _suv_',
       '_gmc_ _terrain_ _suv_', 'tazewell', 'unicoi,tn',
       'asheville/fairview', 'shelby nc', 'nc', 'gray tn', 'gray tn.',
       'obo', 'unicoi tn', 'old fort, nc', 'tricities',
       'asheville and surrounding', 'haywood county', 'greenville, sc',
       'by avl airport', 'by asheville airport', '821 riverside dr',
       'rosman', 'saluda', 'forest city',
       '100% financing available thru greensky credit wac', 'w. avl',
       'murphy, nc', 'benson', 'charlotte street', 'anderson sc',
       'anderson', 'buncombe/mcdowell', '28768', 'local', 'columbus, nc',
       '39 crabapple lane, asheville, nc', 'lake toxaway',
       'to $525, in asheville', 'and $375, in asheville',
       'asheville, grenville, charlotte', 'elizabethton',
       'pigeon forge tenn', 'cedar mountain', 'asheville/alexander',
       'or make an offer! in asheville', 'n asheville', 'sevierville, tn',
       'asheville montford', 'or make an offer, in asheville',
       'to $160, in asheville', 'chattanooga', 'candler/west asheville',
       'sylva nc', 'turtletown, tn', 'almond',
       'asheville and surrounding areas', 'greenwood sc', 'nebo nc',
       'macon, swain, jackson', 'lansing', 'woodfin', 'nc us', '28704',
       'tryn/columbus, nc', 'nc/sc', 'tryon, nc', 'tryon/columbus nc',
       'highland brewing', 'bristol,va.', 'wartburg,tn.', 'sc us',
       'northeast ga.', 'spartanburg,sc', 'bostic nc', 'gaffney s.c.',
       '539 new leicester hwy asheville', 'cherryville, nc', 'valdese',
       'chimney rock', 'western n.c.', 'ashvl, nc area', 'hildebran',
       'marshall, nc', 'flat rock, nc', 'kingsport, tn.', 'raleigh',
       'pisgah forest', 'hendersonville n.c.', 'mooresboro', 'n. raleigh',
       'zebulon', 'east flat rock', '550', 'hiawassee ga.', 'toccoa,ga',
       '28778 cayce st , albemarle, nc', 'burlington', 'waynesville nc',
       'durham, nc', 'inman, s.c. usa', 'inman',
       'good anywhere on biltmore property', 'spruce pine, nc',
       'asheville/candler', '1536 howard gap rd, hendersonville nc',
       'salisbury', 'livingston', 'vignettes of north carolina',
       'asheville, hendersonville area', '92 crayton road',
       'ellenboro, nc', 'lenoir n.c.', 'greeneville', 'va', 'clyde, nc',
       'lake junaluska next to bojangels', 'milledgeville', 'overton',
       'greer', 'new york', 'adheville', 'chattanooga, tn',
       'greenville tn', 'fletcher, nc', 'murphy nc',
       'murphy cherokee county nc', '28714', 'trs', 'eixabethton',
       'middle georgia', 'reynolds-fairview', 'pit',
       'wears valley / pigeon forge, tn', 'arden, n.c.', 'greensboro,nc',
       'piedmont sc', 'mtn.home nc', '326 litwin dr thomasville nc',
       'jonesborough', 'wavl', 'peachtree st, arden, nc',
       'canton, clyde, candler', 'blairsville ga', 'cocke county',
       'winston salem', 'naples/fletcher', 'winston-salem', 'atlanta',
       'subaru impreza', 'canton, candler, asheville, waynesville',
       'spartanburg greenville', 'penrose', 'asheville marshall',
       'rooted at regeneration station booth 48', '120 delaware ave',
       'hickory nc', 'bittersweet antiques swannanoa, nc',
       'valuecargovans.com', 'charlotte', 'mills river, n.c', 'saluda, nc',
       'e. asheville', 'polk nc', 'dandridge, tn', 'mooresville',
       '*2016* *chrysler* *200* *s* *sedan* *leather* *onl'], dtype=object)

In [293]:
locations_to_change = [('asheville', 'asheville, nc'), ('cowpens', 'cowpens, nc'), ('hendersonville', 'hendersonvlle, nc'),
                       ('tryon nc', 'tryon, nc'), ('fletcher', 'fletcher, nc'), ('franklin nc', 'franklin, nc'),
                       ('burnsville', 'burnsville, nc'), ('flat rock', 'flat rock, nc'), ('farview', 'fairview, nc'),
                       ('weaverville', 'weaverville, nc'), ('mills river', 'mills river, nc'), 
                       ("lake junaluska location", 'lake junaluska, nc'), ('bristol tn', 'bristol, tn'),
                       ('calhoun, ga.', 'calhoun, ga'), ('canton', 'canton, nc'),
                       ("alan's jewelry & pawn cherokee", 'whittier, nc'), ("sweet", "asheville, nc"),
                       ('horse shoe', 'horse shoe, nc'), ('reynolds', 'reynolds, nc'), ('marion', 'marion, nc'),  
                       ("2314 asheville hwy",'hendersonville, nc'), ('candler', 'candler, nc'),
                       ('brevard', 'brevard, nc'), ("hendersonville/ etowah", 'hendersonville, nc'), 
                       ('west asheville', 'asheville, nc'), ('asheville nc', 'asheville, nc'), 
                       ("cocke county,tn", 'newport, tn'), ('greenville', 'greenville, sc'),
                       ('rutherfordton', 'rutherfordton, nc'), ('rutherfordton nc', 'rutherfordton, nc'),
                       ("great selection!",'asheboro nc'), ('swannanoa', 'swannanoa, nc'), ('spartanburg sc', 'spartanburg, sc'),
                       ('jonesville', 'jonesville, nc'), ('randleman', 'randleman, nc'), ('clyde', 'clyde, nc'),
                       ('burnsville nc', 'burnsville, nc'), ('canton nc', 'canton, nc'), ('weaverville nc', 'weaverville, nc'),
                       ('morganton', 'morganton, nc'), ('lake lure marine', 'lake lure, nc'), ('sylva', 'sylva, nc'),
                       ('mars hill', 'mars hill, nc'), ('waynesville', 'waynesville, nc'), ('arden', 'arden, nc'),
                       ('s. asheville', 'asheville, nc'), ('taylors', 'taylors, sc'), ("the regeneration station",'asheville, nc'),
                       ('oakley', 'oakley, nc'), ("vintage dreams trading co. booth#246 trs", 'asheville, nc'), 
                       ("3635 e independence blvd", 'charlotte, nc'), ("fletcher/mountain home", 'fletcher, nc'), 
                       ('black mountain', 'black mountain, nc'), ("antique tobacco barn", 'asheville, nc'),
                       ('north asheville', 'asheville, nc'), ('hickory', 'hickory, nc'), ('n. asheville', 'asheville, nc'),
                       ('leicester', 'leicester, nc'), ('franklin', 'franklin, nc'), ('hville', 'east flat rock, nc'),
                       ('morristown tn', 'morristown, tn'),('talbott', 'talbott, tn'), ('sc', 'greenville, sc'),
                       ('harmony', 'harmony, nc'), ('knoxville', 'knoxville, tn'),
                       ('east asheville', 'asheville, nc'), ('e asheville/swannanoa', 'asheville, nc'),
                       ('the village antique & decor sevierville', 'sevierville, tn'), ('newland', 'newland, nc'),
                       ('asheville biltmore', 'asheville, nc'), ('kodak', 'kodak, tn'), ('marshall nc', 'marshall, nc'),
                       ('edneyville', 'edneyville, nc'), ('greenville sc', 'greenville, sc'), 
                       ('east morristown / russellville', 'morristown, nc'), ('marshall', 'marshall, nc'), 
                       ('forest city nc', 'forest city, nc'), ('greensboro', 'greensboro, nc'),
                       ('spruce pine', 'spruce pine, nc'), ('shelby', 'shelby, nc'), ('leicester area', 'leicester, nc'),
                       ('barnardsville', 'barnardsville, nc'), ('lake lure', 'lake lure, nc'),
                       ('burnsville/mars hill', 'burnsville, nc'), ('fletcher/fairview', 'fletcher, nc'),
                       ('tazewell tn', 'tazewell, tn'), ("19 ella lane", 'alexander, nc'), ('bakersville', 'bakersville, nc'),
                       ('mountain home', 'mountain home, nc'), ('gaffney', 'gaffney, sc'), ("n.e. georgia", 'clarkesville, ga'),
                       ('chesnee sc', 'chesnee, sc'), ('spartanburg', 'spartanburg, sc'), ('pineville nc', 'pineville, nc'),
                       ('sweeten creek road', 'asheville, nc'), ('oteen', 'oteen, nc'), ('liberty', 'liberty, sc'),
                       ('liberty sc', 'liberty, sc'), ('simpsonville', 'simpsonville, sc'), ('biltmore', 'asheville, nc'),
                       ('boone nc', 'boone, nc'), ('sc lancaster', 'lancaster, sc'), ('clayton ga', 'clayton, ga'),
                       ('dt avl', 'asheville, nc'), ('sweeten creek antiques', 'asheville, nc'), ('old fort', 'old fort, nc'),
                       ('oldfort', 'old fort, nc'), ('bat cave', 'bat cave, nc'), ('burnsville n.c.', 'burnsville, nc'),
                       ('johnson city', 'johnson city, tn'), ('hendersonville/flatrock', 'hendersonville, nc'), 
                       ('bryson city', 'bryson city, nc'), ('henderson', 'hendersonville, nc'), 
                       ('hendersonville nc', 'hendersonville, nc'), ('fayetteville','fayetteville, nc'), 
                       ('charleston sc', 'charleston, sc'), ('grayson ga', 'grayson, ga'), ('fairview nc', 'fairview, nc'),
                       ('murphy', 'murphy, nc'), ('inman sc', 'inman, sc'), ('alexander', 'alexander, nc'),
                       ('arden nc', 'arden, nc'), ('south asheville', 'asheville, nc'), ('columbus', 'columbus, nc'),
                       ('columbus nc', 'columbus, nc'), ('menagerie mercantile', 'burnsville, nc'), ('asheville,n.c.', 'asheville, nc'),
                       ('southeast asheville, nc', 'asheville, nc'), ('glenville', 'glenville, nc'), ('asheville/fairview, nc', 'asheville, nc'),
                       ('asheville n.c.', 'asheville, nc'), ('southeast asheville, nc', 'asheville, nc'), ('easley', 'easley, sc'),
                       ('501 willard st - durham nc', 'durham, nc'), ('marshill', 'mars hill, nc'), ('marian', 'marion, nc'),
                       ('food lion skatepark', 'asheville, nc'), ('mill spring', 'mill spring, nc'), ('charlotte,n.c.', 'charlotte, nc'),
                       ('bevard', 'brevard, nc'), ('clinton tn', 'clinton, tn'), ('blk. mtn.', 'black mountain, nc'), 
                       ('piedmont', 'piedmont, sc'), ('upstate, sc', 'greenville, sc'), ('49 mount carmel road', 'asheville, nc'),
                       ('flat rock nc', 'flat rock, nc'), ('swannaoa', 'swannanoa, nc'), ('waxhaw', 'waxhaw, nc'),
                       ('downtown asheville', 'asheville, nc'), ('lafollette', 'la follette, tn'),
                       ('south of forrest city', 'forest city, nc'), ('asheville , n c', 'asheville, nc'),
                       ('asheville n c', 'asheville, nc'), ('asheville, n c', 'asheville, nc'), ('marion nc', 'marion, nc'),
                       ('cashiers', 'cashiers, nc'), ('west asheville/candler', 'asheville, nc'), 
                       ('flat creek / weaverville', 'weaverville, nc'), ('boone', 'boone, nc'), ('bon vivant, asheville, nc', 'asheville, nc'),
                       ('etowah', 'etowah, nc'), ('east asheville nc haw creek', 'asheville, nc'), ('sylva n.c.', 'sylva, nc'),
                       ('nebo', 'nebo, nc'), ('asheville,nc', 'asheville, nc'), ('toccoa','toccoa, ga'), ('monroe', 'monroe, nc'),
                       ('charleston', 'charleston, sc'), ('the orange peel', 'asheville, nc'), ('asheville & surrounding area', 'asheville, nc'),
                       ('boiling springs sc', 'boiling springs, sc'), ('drexel/morganton', 'morganton, nc'), 
                       ('lake james family campground', 'marion, nc'), ('fairview/fletchet', 'fairview, nc'), ('cornelia', 'cornelia, nc'),
                       ('sevierville', 'sevierville, tn'), ('n. asheville-common ground', 'asheville, nc'), ('539 new leicester hwy', 'asheville, nc'),
                       ('weaverville n.c', 'weaverville, nc'), ('w n.c weaverville', 'weaverville, nc'), ('asheville n.c', 'asheville, nc'),
                       ('sparta nc', 'sparta, nc'), ('cherokee', 'cherokee, nc'), ('whittier', 'whittier, nc'), ('harriman', 'harriman, tn'),
                       ('ashevile', 'asheville, nc'), ('hendersonville/horse shoe', 'hendersonville, nc'), ('oakley, asheville', 'asheville, nc'),
                       ('south asheville/fletcher', 'asheville, nc'), ('limestone tn', 'limestone, tn'), ('freeburg pianos', 'asheville, nc'),
                       ('calhoun ga', 'calhoun, ga'), ('avl', 'asheville, nc'), ('haywood', 'asheville, nc'), ('clinton, knoxville', 'knoxville, tn'),
                       ('bristol', 'bristol, tn'), ('alexander nc', 'alexander, nc'), ('hot springs', 'hot springs, nc'), 
                       ('kingsport tn', 'kingsport, tn'), ('whittier nc', 'whittier, nc'), ('black mt/asheville', 'asheville, nc'),
                       ('ashville', 'asheville, nc'), ('bostic', 'bostic, nc'), ('asheville / canton', 'asheville, nc'),
                       ('sannanowa', 'swannanoa, nc'), ('boiling spring .sc', 'boiling spring, sc'), ('s carolina', 'moncks corner, sc'),
                       ('cullowhee', 'cullowhee, nc'), ('clover', 'clover, sc'), ('wnc', 'lake junaluska, nc'), ('west buncombe', 'leicester, nc'),
                       ('71 belmont ave', 'asheville, nc'), ('henderson county', 'mountain home, nc'), ('bent creek', 'asheville, nc'),
                       ('s avl', 'asheville, nc'), ('brevard nc', 'brevard, nc'), ('greeneville tn', 'greeneville, tn'),
                       ('maggie valley', 'maggie valley, nc'), ("harrah's cherokee", "cherokee, nc"), ('asheboro', 'asheboro, nc'),
                       ('hagen drive', 'hendersonville, nc'), ('pigeon forge', 'pigeon forge, tn'), ('tazewell', 'tazewell, tn'),
                       ('unicoi,tn', 'unicoi, tn'), ('asheville/fairview', 'asheville, nc'), ('shelby nc', 'shelby, nc'),
                       ('gray tn', 'gray, tn'), ('unicoi tn', 'unicoi, tn'), ('tricities', 'kingsport, tn'),
                       ('asheville and surrounding', 'asheville, nc'), ('haywood county', 'waynesville, nc'), ('by avl airport', 'asheville, nc'),
                       ('by asheville airport', 'asheville, nc'), ('821 riverside dr', 'asheville, nc'), ('rosman', 'rosman, nc'),
                       ('saluda', 'saluda, nc'), ('forest city', 'forest city, nc'), ('w. avl', 'asheville, nc'), ('benson', 'benson, nc'),
                       ('charlotte street', 'asheville, nc'), ('anderson sc', 'anderson, sc'), ('anderson', 'anderson, sc'),
                       ('buncombe/mcdowell', 'asheville, nc'), ('28768', 'penrose, nc'), ('39 crabapple lane', 'asheville, nc'),
                       ('lake toxaway', 'lake toxaway, nc'), ('to $525, in asheville', 'asheville, nc'), ('and $375, in asheville', 'asheville, nc'),
                       ('asheville, grenville, charlotte', 'asheville, nc'), ('elizabethton', 'elizabethton, tn'), ('pigeon forge tenn', 'pigeon forge, tn'),
                       ('cedar mountain', 'cedar mountain, nc'), ('asheville/alexander', 'asheville, nc'), 
                       ('or make an offer! in asheville', 'asheville, nc'), ('n asheville', 'asheville, nc'), ('asheville montford', 'asheville, nc'),
                       ('or make an offer, in asheville', 'asheville, nc'), ('to $160, in asheville', 'asheville, nc'),
                       ('chattanooga', 'chattanooga, tn'), ('candler/west asheville', 'asheville, nc'), ('sylva nc', 'sylva, nc'),
                       ('almond', 'almond, nc'), ('asheville and surrounding areas', 'asheville, nc'), ('greenwood sc', 'greenwood, sc'),
                       ('nebo nc', 'nebo, nc'), ('macon, swain, jackson', 'franklin, nc'), ('lansing', 'lansing, nc'), ('woodfin', 'asheville, nc'),
                       ('28704', 'arden, nc'), ('tryn/columbus, nc', 'columbus, nc'), ('tryon/columbus nc', 'columbus, nc'),
                       ('highland brewing', 'asheville, nc'), ('bristol,va.', 'bristol, va'), ('wartburg,tn.', 'wartburg, tn'),
                       ('spartanburg,sc', 'spartanburg, sc'), ('bostic nc', 'bostic, nc'), ('gaffney s.c.', 'gaffney, sc'),
                       ('539 new leicester hwy asheville', 'asheville, nc'), ('valdese', 'valdese, nc'), ('chimney rock', 'lake lure, nc'),
                       ('ashvl, nc area', 'asheville, nc'), ('hildebran', 'hildebran, nc'), ('kingsport, tn.', 'kingsport, tn'),
                       ('raleigh', 'raleigh, nc'), ('pisgah forest', 'pisgah forest, nc'), ('hendersonville n.c.', 'hendersonville, nc'),
                       ('mooresboro', 'mooresboro, nc'), ('n. raleigh', 'raleigh, nc'), ('zebulon', 'zebulon, nc'), 
                       ('east flat rock', 'east flat rock, nc'), ('550', 'arden, nc'), ('hiawassee ga.', 'hiawassee, ga'),
                       ('toccoa,ga', 'toccoa, ga'), ('28778 cayce st , albemarle, nc', 'albemarle, nc'), ('burlington', 'burlington, nc'),
                       ('waynesville nc', 'waynesville, nc'), ('inman', 'inman, sc'), ('good anywhere on biltmore property', 'asheville, nc'),
                       ('asheville/candler', 'asheville, nc'), ('536 howard gap rd, hendersonville nc', 'hendersonville nc'),
                       ('salisbury', 'salisbury, nc'), ('livingston', 'livingston, tn'), ('vignettes of north carolina', 'twin brooks, nc'),
                       ('asheville, hendersonville area', 'asheville, nc'), ('92 crayton road', 'asheville, nc'), 
                       ('lenoir n.c.', 'lenoir, nc'), ('greeneville', 'greeneville, tn'), ('lake junaluska next to bojangels', 'lake junaluska, nc'),
                       ('milledgeville', 'milledgeville, ga'), ('overton', 'overton, tn'), ('greer', 'greer, sc'), ('adheville', 'asheville, nc'),
                       ('greenville tn', 'greenville, tn'), ('murphy nc', 'murphy, nc'), ('murphy cherokee county nc', 'murphy, nc'),
                       ('28714', 'burnsville, nc'), ('trs', 'asheville, nc'), ('eixabethton', 'elizabethton, tn'),
                       ('reynolds-fairview', 'fairview, nc'), ('pit', 'asheville, nc'), ('wears valley / pigeon forge, tn', 'pigeon forge, tn'),
                       ('arden, n.c.', 'arden, nc'), ('greensboro,nc', 'greensboro, nc'), ('piedmont sc', 'piedmont, sc'),
                       ('mtn.home nc', 'mountain home, nc'), ('326 litwin dr thomasville nc', 'thomasville, nc'), ('jonesborough', 'jonesborough, tn'),
                       ('wavl', 'asheville, nc'), ('peachtree st, arden, nc', 'arden, nc'), ('canton, clyde, candler', 'canton, nc'),
                       ('blairsville ga', 'blairsville, ga'), ('cocke county', 'newport, tn'), ('winston salem', 'winston-salem, nc'),
                       ('naples/fletcher', 'fletcher, nc'), ('winston-salem', 'winston-salem, nc'), ('atlanta', 'atlanta, ga'),
                       ('canton, candler, asheville, waynesville', 'canton, nc'), ('spartanburg greenville', 'spartanburg, sc'),
                       ('penrose', 'penrose, nc'), ('asheville marshall', 'marshall, nc'), 
                       ('rooted at regeneration station booth 48', 'asheville, nc'), ('120 delaware ave', 'asheville, nc'),
                       ('hickory nc', 'hickory, nc'), ('bittersweet antiques swannanoa, nc', 'swannanoa, nc'), ('charlotte', 'charlotte, nc'),
                       ('mills river, n.c', 'mills river, nc'), ('e. asheville', 'asheville, nc'), ('polk nc', 'polk, nc'), ('mooresville', 'mooresville, nc'),
                       ('dawsonville, ga.', 'dawsonville, ga'), ('chadbourn nc', 'chadbourn, nc'), ('rutledge,tn', 'rutledge, tn'),
                       ('fairview', 'fairview, nc'), ('1536 howard gap rd, hendersonville nc', 'hendersonville, nc'),
                       ('none', 'unspecified'), ('tryon,nc', 'tryon, nc'),('waynesvile, nc' ,'waynesville, nc'), ('hiawasssee, ga', 'hiawassee, ga'),
                       ('boiling spring, sc', 'boiling springs, sc')
                      ]

locations_to_drop = ["subaru forester", "_jeep_ _wrangler unlimited_ _suv_", "we finance all types of credit!",
                     "buy here pay here w/ credit reporting!!!", "any", "_kia_ _soul_ _wagon_", 
                     "_jeep_ _wrangler unlimited_ _suv_", "stock#p6155", "stock#210816", "sc/nc", "_nissan_ _quest_ _van_",
                     "_chrysler_ _300-series_ _sedan_", "_dodge_ _dart_ _sedan_", '_ford_ _edge_ _suv_', '_ford_ _f-150_ _truck_',
                     '_jeep_ _compass_ _suv_', '_ram_ _cargo van_ _van_', '_ford_ _super duty f-350 drw chassis cab', 'colorado',
                     '_ford_ _escape_ _suv_', '_dodge_ _charger_ _sedan_', "nc, sc, ga, tn", '*2013* *dodge* *ram* *1500* *regular* *cab* *hfe*',
                     '*2006* *nissan* *altima* *2.5s* *sedan* *special*', '*2013* *dodge* *ram* *1500* *quad* *cab* *2wd* *sl', 
                     '*2010* *chevrolet* *silverado* *1500* *crew* *cab*', '*2006* *ford* *f-350* *sd* *crew* *cab* *lariat* *',
                     '*2014* *ford* *f-150* *supercrew* *4x4* *fx4* *roc', '*2014* *chrysler* *town* *&* *country* *touring* *',
                     '*2012* *gmc* *sierra* *1500* *crew* *cab* *4x4* *z', '*2012* *toyota* *tacoma* *prerunner* *double* *cab',
                     "27284_we_finance", "polk county nc", "upstate sc", "we_finance_27284", 'greeneville honda 730 west andrew johnso',
                     '_chevrolet_ _suburban_ _suv_', '_dodge_ _grand caravan_ _van_', '_nissan_ _rogue_ _suv_',
                     '_jeep_ _grand cherokee_ _suv_', '_gmc_ _terrain_ _suv_', "100% financing available thru greensky credit wac",
                     "local", "nc us", "nc/sc", "sc us", "northeast ga.", "western n.c.", "inman, s.c. usa", "va", "new york",
                     "middle georgia", "subaru impreza", "valuecargovans.com", "*2016* *chrysler* *200* *s* *sedan* *leather* *onl", 'nc',
                     'obo' 
                     ]

In [294]:
drop_location_values(locations_to_drop, 'cl')

In [295]:
adjust_location_values(locations_to_change, 'cl')

In [296]:
cl_items_df['Location'].unique()

array(['Asheville, NC', 'Cowpens, NC', 'Hendersonville, NC', 'Tryon, NC',
       'Fletcher, NC', 'Franklin, NC', 'Unspecified', 'Burnsville, NC',
       'Flat Rock, NC', 'Fairview, NC', 'Greeneville, TN',
       'Weaverville, NC', 'Mills River, NC', 'Lake Junaluska, NC',
       'Bristol, TN', 'Calhoun, GA', 'Canton, NC', 'Whittier, NC',
       'Bostic, NC', 'Horse Shoe, NC', 'Reynolds, NC', 'Marion, NC',
       'Waynesville, NC', 'Candler, NC', 'Brevard, NC', 'Highlands, NC',
       'Knoxville, TN', 'Newport, TN', 'Greenville, SC',
       'Rutherfordton, NC', 'Hickory, NC', 'Asheboro, NC', 'Swannanoa, NC',
       'Spartanburg, SC', 'Jonesville, NC', 'Gaffney, SC', 'Randleman, NC',
       'Clyde, NC', 'Maryville, TN', 'Rutledge, TN', 'Morganton, NC',
       'Lake Lure, NC', 'Sylva, NC', 'Mars Hill, NC', 'Dawsonville, GA',
       'Arden, NC', 'Chadbourn, NC', 'Taylors, SC', 'Oakley, NC',
       'Charlotte, NC', 'Black Mountain, NC', 'Leicester, NC',
       'East Flat Rock, NC', 'Morristown, TN', 'Talbott, TN',
       'Harmony, NC', 'Sevierville, TN', 'Newland, NC', 'Kodak, TN',
       'Marshall, NC', 'Edneyville, NC', 'Morristown, NC',
       'Forest City, NC', 'Greensboro, NC', 'Spruce Pine, NC',
       'Shelby, NC', 'Barnardsville, NC', 'Tazewell, TN', 'Alexander, NC',
       'Bakersville, NC', 'Mountain Home, NC', 'Clarkesville, GA',
       'Chesnee, SC', 'Pineville, NC', 'Elizabethton, TN', 'Oteen, NC',
       'Liberty, SC', 'Simpsonville, SC', 'Boone, NC', 'Clayton, GA',
       'Old Fort, NC', 'Bat Cave, NC', 'Johnson City, TN',
       'Bryson City, NC', 'Fayetteville, NC', 'Charleston, SC',
       'Grayson, GA', 'Murphy, NC', 'Inman, SC', 'Douglas, GA',
       'Columbus, NC', 'Glenville, NC', 'Easley, SC', 'Durham, NC',
       'Mill Spring, NC', 'Clinton, TN', 'Piedmont, SC', 'Hot Springs, NC',
       'Waxhaw, NC', 'La Follette, TN', 'Cashiers, NC', 'Etowah, NC',
       'Nebo, NC', 'Yadkinville, NC', 'Toccoa, GA', 'Monroe, NC',
       'Boiling Springs, SC', 'Cornelia, NC', 'Sparta, NC', 'Cherokee, NC',
       'Harriman, TN', 'Limestone, TN', 'Kingsport, TN', 'Laurel Hill, NC',
       'Andrews, NC', 'Moncks Corner, SC', 'Cullowhee, NC', 'Clover, SC',
       'Maggie Valley, NC', 'Hiawassee, GA', 'Pigeon Forge, TN',
       'Unicoi, TN', 'Gray, TN', 'Rosman, NC', 'Saluda, NC', 'Benson, NC',
       'Anderson, SC', 'Penrose, NC', 'Lake Toxaway, NC',
       'Cedar Mountain, NC', 'Chattanooga, TN', 'Turtletown, TN',
       'Almond, NC', 'Greenwood, SC', 'Lansing, NC', 'Wartburg, TN',
       'Cherryville, NC', 'Hildebran, NC', 'Raleigh, NC',
       'Pisgah Forest, NC', 'Mooresboro, NC', 'Zebulon, NC',
       'Albemarle, NC', 'Burlington, NC', 'Salisbury, NC',
       'Livingston, TN', 'Twin Brooks, NC', 'Ellenboro, NC', 'Lenoir, NC',
       'Milledgeville, GA', 'Overton, TN', 'Greer, SC', 'Thomasville, NC',
       'Jonesborough, TN', 'Blairsville, GA', 'Winston-Salem, NC',
       'Atlanta, GA', 'Polk, NC', 'Dandridge, TN', 'Mooresville, NC'], dtype=object)

In [297]:
#checking count of items with unknown location
len(cl_items_df[cl_items_df.Location == 'Unspecified'])

405

In [298]:
#checking for any remaining duplicates
print(cl_items_df[cl_items_df.duplicated(subset=['Title','Price','Location'], keep=False)])

#dropping any more remaining duplicates
cl_items_df.drop_duplicates(subset=['Title', 'Location', 'Price'],inplace=True)

#resetting index
cl_items_df.reset_index(inplace=True, drop=True)
cl_items_df[cl_items_df.duplicated(subset=['Title','Price','Location'], keep=False)]

                                   Title       Location   Price  \
1623               LeMond recumbent bike  Asheville, NC   500.0
1624               LeMond recumbent bike  Asheville, NC   500.0
1693  1998 Toyota Tacoma SR5 4x4 Ext Cab   Anderson, SC  7900.0
1695  1998 Toyota Tacoma SR5 4x4 Ext Cab   Anderson, SC  7900.0

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Description  \
1623                                                                                                                                                                                                                                                                                                                                                                                                                LeMond recumbent bike. Cordless in good shape. Retail is $2600. $500 or May trade.
1624                                                                                                                                                                                                                                                                                                                                                                         LeMond recumbent bike $2500 retail. Looking to trade for tools, canoe,kayak, paint sprayer, etc. will consider any trade.
1693  I have for sale a Nice 1998 Toyota Tacoma, automatic transmission, 4wd with manual locking hubs, power windows and door locks, power sliding back glass, cruise control, 3.4l v6 with 147k Miles. Just had it completely serviced including new plugs and wires, water pump, timing belt, oil and filter and transmission service. It's a one owner truck with NO rust. It's been garage kept as you can see paint looks good. That's the original paint. Never been wrecked. If interested call
1695  I have for sale a Nice 1998 Toyota Tacoma, automatic transmission, 4wd with manual locking hubs, power windows and door locks, power sliding back glass, cruise control, 3.4l v6 with 147k Miles. Just had it completely serviced including new plugs and wires, water pump, timing belt, oil and filter and transmission service. It's a one owner truck with NO rust. It's been garage kept as you can see paint looks good. That's the original paint. Never been wrecked. If interested call

                                                                                    Url  \
1623       https://asheville.craigslist.org/spo/d/lemond-recumbent-bike/6498809780.html
1624       https://asheville.craigslist.org/bar/d/lemond-recumbent-bike/6503000567.html
1693  https://asheville.craigslist.org/cto/d/1998-toyota-tacoma-sr5-4x4/6495554420.html
1695  https://asheville.craigslist.org/cto/d/1998-toyota-tacoma-sr5-4x4/6495545778.html

       Latitude   Longitude
1623       None        None
1624       None        None
1693  34.319800  -82.657400
1695  34.319800  -82.657400

Empty DataFrame
Columns: [Title, Location, Price, Description, Url, Latitude, Longitude]
Index: []

In [299]:
#replacing 'None' with None for float type conversion
cl_items_df['Latitude'].replace('None',None,inplace=True)
cl_items_df['Longitude'].replace('None',None,inplace=True)

#converting to floats
cl_items_df['Latitude'] = cl_items_df['Latitude'].astype(float)
cl_items_df['Longitude'] = cl_items_df['Longitude'].astype(float)

In [300]:
cl_items_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2724 entries, 0 to 2723
Data columns (total 7 columns):
Title          2724 non-null object
Location       2724 non-null object
Price          2721 non-null float64
Description    2685 non-null object
Url            2724 non-null object
Latitude       2724 non-null float64
Longitude      2724 non-null float64
dtypes: float64(3), object(4)
memory usage: 149.0+ KB

In [301]:
cl_items_df.head()

,Title,Location,Price,Description,Url,Latitude,Longitude
0,2013 Yamaha FJR 1300,"Asheville, NC",7500.0,"2013 Yamaha FJR 1300 Sport Touring, 4 cylinder, 12.120 miles, silver, cruise control, traction control, ABS brakes, heated hand grips, Two Brothers exhaust, handle bar risers, 6.5 gal. gas tank, adjustable windshield, saddlebags, excellent condition, very clean. $ 7.500 (828) 250-0373 WWW.GREENVALLEYCARS.COM",https://asheville.craigslist.org/mcd/d/2013-yamaha-fjr-1300/6513320993.html,35.599694,-82.628866
1,2014 Honda Accord White 41k,"Cowpens, NC",10995.0,"2014 Honda Accord Automatic, White , On Tan, It has Only 41,980 Miles It Has Spoiler, Power Windows, and Mirrors, Tan Cloth Seats, Power Seats, 4 Cylinder, 4 Door, Radio, 6 CD Changer, FM,AM,CD, XM Radio, Bluetooth, Back up Camera, Side and Curtain Air Bag, 16 Inch Factory Wheels with Firestone Great Tires, Tinted Glass, And Much More, Clean On inside, Runs and Drives Like New, Call Me for more info, 864-266-6936 Willing to Negotiate if offer is fair..... honda, bmw, crv, mercedes, ford, maz...",https://asheville.craigslist.org/ctd/d/2014-honda-accord-white-41k/6513312696.html,35.039000,-81.822000
2,Pet Crate,"Hendersonville, NC",50.0,Petmate Pet Porter for large dogs - plastic shell - wire door,https://asheville.craigslist.org/for/d/pet-crate/6513308129.html,35.257061,-82.505744
3,1970's Fender Vibrosonic Amplifier,"Tryon, NC",750.0,"Vintage 70's Fender Vibrosonic Reverb guitar amplifier. 15"" Fender pro series speaker and uses 6L6 tubes. Great shape!",https://asheville.craigslist.org/msg/d/1970s-fender-vibrosonic/6513308239.html,35.257061,-82.505744
4,Poll Parrot and Weatherbird Comics,"Fletcher, NC",10.0,Poll Parrot and Weatherbird Comics - all three only $10. Please email if interested.,https://asheville.craigslist.org/clt/d/poll-parrot-and-weatherbird/6500112360.html,35.257061,-82.505744

In [302]:
#exporting df's to csv's
fb_items_df.to_csv('fb_items_cleaned.csv', index=False)
lg_items_df.to_csv('lg_items_cleaned.csv', index=False)
cl_items_df.to_csv('cl_items_cleaned.csv', index=False)

In [303]:
#creating a df with all items combined
all_items_df = pd.concat([lg_items_df,cl_items_df,fb_items_df], axis=0, ignore_index=True)
all_items_df.to_csv('all_items_cleaned.csv', index=False)

In [304]:
ls

Craigslist_items.json               fb_used_items_filtered.txt
FBM_selenium.py                     final_project/
Facebook_items.json                 final_project_EDA_and_NLP.ipynb
Letgo_items.json                    final_project_data_wrangling.ipynb
all_items_cleaned.csv               geckodriver.log
cl_items_cleaned.csv                lg_items_cleaned.csv
cl_used_items_filtered.txt          lg_used_items_filtered.txt
connxchange_FBM.py                  notes.txt
fb_items_cleaned.csv